(() => {
  "use strict";

  const STORAGE_KEY = "fifa9-ui-language";
  const supported = new Set(["tr", "en"]);
  const initial = supported.has(localStorage.getItem(STORAGE_KEY))
    ? localStorage.getItem(STORAGE_KEY)
    : ((navigator.language || "tr").toLowerCase().startsWith("en") ? "en" : "tr");

  const dictionary = {
    "Ana menü": "Main menu",
    "Dil seçimi": "Language selection",
    "Türkçe": "Turkish",
    "Menüyü aç": "Open menu",
    "Kapat": "Close",
    "Dashboard": "Dashboard",
    "Kura & Oyuncular": "Draw & Players",
    "League Phase": "League Phase",
    "Altın Grup": "Gold Group",
    "Gümüş Grup": "Silver Group",
    "Eleme Aşaması": "Knockout Stage",
    "Turnuva Arşivi": "Tournament Archive",
    "Tüm Zamanlar": "All-Time Records",
    "Veri & Yedek": "Data & Backup",
    "Canlı bağlantı hazırlanıyor": "Preparing live connection",
    "Bağlanıyor": "Connecting",
    "Bağlanıyor...": "Connecting...",
    "Yerel mod": "Local mode",
    "Bulut kurulumu bekleniyor": "Cloud setup pending",
    "Veri yükleniyor": "Loading data",
    "Kaydediliyor": "Saving",
    "Canlı · kaydedildi": "Live · saved",
    "Canlı · yönetici": "Live · administrator",
    "Canlı · izleyici": "Live · viewer",
    "Yeniden bağlanıyor": "Reconnecting",
    "Bağlantı hatası": "Connection error",
    "Canlı bağlantı": "Live connection",
    "Yedek Al": "Create Backup",
    "Yönetici Girişi": "Admin Login",
    "Yönetici · Çıkış": "Admin · Sign Out",
    "Bulut Kurulumu": "Cloud Setup",
    "Sonuç girişi yalnızca yöneticiye açıktır": "Result entry is restricted to the administrator",
    "Son güncelleme:": "Last update:",
    "Turnuva Merkezi": "Tournament Hub",
    "16 oyunculu League Phase, Altın ve Gümüş ligleri, üç maçlık eleme serileri ve sekiz turnuvalık tarihçe tek bir merkezde. Sonuçlar yönetici tarafından girilir; puan tabloları, sıralamalar ve eşleşmeler bütün cihazlarda otomatik güncellenir.": "A 16-player League Phase, Gold and Silver leagues, best-of-three knockout series and the history of eight tournaments in one hub. Results are entered by the administrator; standings, rankings and brackets update automatically on every device.",
    "Canlı Turnuvaya Git": "Open Live Tournament",
    "Oyuncuları Kaydet & Kura Çek": "Save Players & Run Draw",
    "8 Turnuvalık Arşivi Aç": "Open 8-Tournament Archive",
    "WhatsApp'ta Paylaş": "Share on WhatsApp",
    "Turnuva Durumu": "Tournament Status",
    "Tamamlanan lig maçı": "League matches completed",
    "Altın + Gümüş": "Gold + Silver",
    "İkinci aşama maçı": "Second-stage matches",
    "Şampiyon": "Champion",
    "Henüz Belirlenmedi": "Not Yet Decided",
    "FIFA 9 Şampiyonu": "FIFA 9 Champion",
    "Final yolu devam ediyor": "The road to the final continues",
    "Turnuva Yol Haritası": "Tournament Roadmap",
    "Kura çekiminden kupaya kadar otomatik aşama kontrolü.": "Automatic stage control from the draw to the trophy.",
    "Canlı League Phase Tablosu": "Live League Phase Table",
    "İlk 6 Altın Gruba, 7–12 Gümüş Gruba yükselir.": "Positions 1–6 advance to the Gold Group; 7–12 advance to the Silver Group.",
    "Tümünü Gör": "View All",
    "Henüz kura çekilmedi": "The draw has not been made yet",
    "16 oyuncuyu kaydedip League Phase fikstürünü oluşturduğunda canlı puan tablosu burada görünecek.": "The live standings will appear here after you register 16 players and generate the League Phase schedule.",
    "Kura Sayfasına Git": "Go to Draw Page",
    "Turnuva İstatistiği": "Tournament Statistics",
    "Geçmiş sekiz turnuvanın kalıcı kayıtları.": "Permanent records from the previous eight tournaments.",
    "Sıralamayı Aç": "Open Rankings",
    "Tamamlanan turnuva": "Completed tournaments",
    "FIFA 1’den FIFA 8’e kadar arşivlendi.": "Archived from FIFA 1 through FIFA 8.",
    "Kayıtlı tarihî maç": "Recorded historical matches",
    "Takımlar, skorlar ve final aşamaları dahil.": "Including teams, scores and final stages.",
    "Tarihî gol": "Historical goals",
    "Tüm turnuvaların birleşik gol arşivi.": "Combined goal archive for all tournaments.",
    "Tüm zamanlar lideri": "All-time leader",
    "Arşiv yükleniyor": "Loading archive",
    "FIFA 9 mevcut lideri": "Current FIFA 9 leader",
    "Şampiyonlar Kulübü": "Champions Club",
    "Şampiyonluk": "Titles",
    "podyum": "podiums",
    "Kura": "Draw",
    "16 oyuncu ve 6 maçlık fikstür": "16 players and a 6-match schedule",
    "48 maç · tek lig tablosu": "48 matches · one league table",
    "Altın / Gümüş": "Gold / Silver",
    "İki ligde toplam 30 maç": "30 matches across two leagues",
    "Eleme Serileri": "Knockout Series",
    "Çeyrek final ve yarı final": "Quarter-finals and semi-finals",
    "Büyük Final": "Grand Final",
    "Tek maç · tek şampiyon": "Single match · one champion",
    "Kura Bekleniyor": "Awaiting Draw",
    "League Phase Devam Ediyor": "League Phase in Progress",
    "Altın/Gümüş Aşaması Hazır": "Gold/Silver Stage Ready",
    "Altın/Gümüş Grupları": "Gold/Silver Groups",
    "Eleme Kurası Hazır": "Knockout Draw Ready",
    "Turnuva Tamamlandı": "Tournament Completed",
    "16 Oyuncu Kadrosu": "16-Player Roster",
    "İsimler tamamlandığında sistem altı turluk, tekrarsız League Phase fikstürünü üretir.": "Once all names are entered, the system generates a six-round League Phase schedule with no repeat opponents.",
    "oyuncu": "players",
    "Oyuncu": "Player",
    "İsimleri Toplu Yapıştır": "Paste Names in Bulk",
    "Kura Çek & 6 Turluk Fikstürü Oluştur": "Run Draw & Generate 6-Round Schedule",
    "Canlı izleyici modundasın. Oyuncu ve kura yönetimi yalnızca turnuva yöneticisine açıktır.": "You are in live viewer mode. Player and draw management is restricted to the tournament administrator.",
    "Fikstür oluşturuldu.": "The schedule has been generated.",
    "İsimleri değiştirebilirsin; ancak oyuncu sıraları ve maç kimlikleri korunur. Tamamen yeni bir kura için “FIFA 9 Verisini Sıfırla” işlemini kullan.": "You may change the names, but player slots and match IDs will remain unchanged. Use “Reset FIFA 9 Data” for a completely new draw.",
    "Kura ve oyuncu listesi canlı olarak yayımlanıyor.": "The draw and player list are being published live.",
    "Nihai Format": "Final Format",
    "FIFA 9 · League Phase sistemi": "FIFA 9 · League Phase system",
    "16 oyuncu, tek tablo, oyuncu başına 6 maç; toplam 48 maç.": "16 players, one table, 6 matches per player; 48 matches in total.",
    "İlk 6 Altın, sonraki 6 Gümüş; son 4 elenir. Puanlar taşınır.": "The top 6 enter Gold, the next 6 enter Silver; the bottom 4 are eliminated. Points carry over.",
    "İkinci Lig Aşaması": "Second League Stage",
    "Her grupta 6 oyuncu ve kişi başı 5 maç; toplam 30 maç.": "Six players in each group and five matches per player; 30 matches in total.",
    "Altın 1 doğrudan yarı final; diğer eşleşmeler üç maçta iki galibiyet.": "Gold 1 advances directly to the semi-final; the other ties are best-of-three series.",
    "Tek maç; eşitlikte uzatma ve penaltılar.": "Single match; extra time and penalties apply if level.",
    "Puan eşitliğinde sırasıyla genel averaj, atılan gol, galibiyet sayısı ve alfabetik sıra uygulanır.": "Ties on points are resolved by goal difference, goals scored, wins and then alphabetical order.",
    "Oluşturulan Kura": "Generated Draw",
    "League Phase Fikstürü": "League Phase Schedule",
    "Her oyuncu altı farklı rakiple karşılaşır.": "Each player faces six different opponents.",
    "Sonuç Girişine Git": "Go to Result Entry",
    "League Phase henüz oluşturulmadı": "The League Phase has not been generated yet",
    "Önce 16 oyuncuyu kaydet ve kura çek. Sistem her oyuncuya altı farklı rakip atayacak.": "Register 16 players and run the draw first. The system will assign six different opponents to each player.",
    "League Phase'e Git": "Go to League Phase",
    "ROUND 1": "ROUND 1",
    "16 oyuncu · 6 tur · tek puan tablosu · ilk 12 bir sonraki aşamaya yükselir.": "16 players · 6 rounds · one table · the top 12 advance to the next stage.",
    "Tamamlanan Maç": "Completed Matches",
    "Puan Tablosu": "Standings",
    "Puan · averaj · atılan gol · galibiyet sıralaması.": "Ranked by points, goal difference, goals scored and wins.",
    "Altın / Gümüş Gruplarını Oluştur": "Generate Gold / Silver Groups",
    "Maç Merkezi": "Match Centre",
    "Bir maça tıklayarak skor ve takım bilgilerini gir.": "Click a match to enter the score and team details.",
    "Gümüş Bölgesi": "Silver Qualification Zone",
    "Gümüş Gruba yükselir": "Advances to the Silver Group",
    "Altın Bölgesi": "Gold Qualification Zone",
    "Altın Gruba yükselir": "Advances to the Gold Group",
    "Elenecek Bölge": "Elimination Zone",
    "Turnuvaya veda eder": "Eliminated from the tournament",
    "Grup henüz oluşmadı": "Group not generated yet",
    "League Phase’in 48 maçı tamamlandıktan sonra ilk 12 oyuncu iki gruba ayrılır.": "After all 48 League Phase matches are completed, the top 12 players are divided into two groups.",
    "ROUND 2": "ROUND 2",
    "League Phase puanları ve averajları taşındı. Her oyuncu bu aşamada 5 ek maç yapar.": "League Phase points and goal differences carry over. Each player plays five additional matches in this stage.",
    "Grup Maçı": "Group Matches",
    "Tamamlanan ikinci aşama maçı": "Second-stage matches completed",
    "Kişi Başı Ek Maç": "Additional Matches per Player",
    "Puanlara ve averaja eklenir": "Added to points and goal difference",
    "Kümülatif Puan Durumu": "Cumulative Standings",
    "sonuçları birlikte hesaplanır.": "results are calculated together.",
    "Eleme Eşleşmelerini Oluştur": "Generate Knockout Ties",
    "Grup Fikstürü": "Group Schedule",
    "Beş turluk tek lig usulü.": "Five-round single round-robin format.",
    "Diğer grubun tamamlanması bekleniyor.": "Waiting for the other group to be completed.",
    "ROAD TO GLORY": "ROAD TO GLORY",
    "Çeyrek final ve yarı final: üç maçta iki galibiyet. Büyük final: tek maç.": "Quarter-finals and semi-finals: best of three. Grand Final: single match.",
    "Şampiyonluk Yolu": "Road to the Championship",
    "Seri maçlarına sırayla tıkla; iki galibiyet alan oyuncu otomatik olarak sonraki tura taşınır.": "Open the series matches in order; the first player to two wins advances automatically.",
    "Çeyrek Final 1": "Quarter-final 1",
    "Çeyrek Final 2": "Quarter-final 2",
    "Çeyrek Final 3": "Quarter-final 3",
    "Yarı Final 1": "Semi-final 1",
    "Yarı Final 2": "Semi-final 2",
    "Kazanan Yarı Final 2’ye yükselir.": "The winner advances to Semi-final 2.",
    "Kazanan, Altın Grup lideriyle Yarı Final 1’de oynar.": "The winner faces the Gold Group leader in Semi-final 1.",
    "Seri Kuralları": "Series Rules",
    "Uygulanan eleme mantığı.": "Knockout format in use.",
    "Lig liderliğinin ödülü.": "Reward for winning the league.",
    "Üç maçlık seri; iki galibiyet alan tur atlar.": "Best-of-three series; the first to two wins advances.",
    "Önceki eşleşme sonucu bekleniyor.": "Waiting for the previous tie to be completed.",
    "BÜYÜK FİNAL · TEK MAÇ": "GRAND FINAL · SINGLE MATCH",
    "Yarı final galipleri bekleniyor.": "Waiting for the semi-final winners.",
    "Final sonucunu girmek için tıkla": "Click to enter the final result",
    "Final sonucu bekleniyor": "Awaiting final result",
    "ŞAMPİYON": "CHAMPION",
    "Tur atlayan:": "Advanced:",
    "Maç": "Match",
    "TUR": "ROUND",
    "SKOR GİR": "ENTER SCORE",
    "BEKLENİYOR": "PENDING",
    "Takım seçilmedi": "Team not selected",
    "Penaltı galibi:": "Penalty winner:",
    "Sonuç girişi için tıkla": "Click to enter result",
    "Canlı sonuç bekleniyor": "Awaiting live result",
    "Oyuncu": "Player",
    "Form": "Form",
    "TURNUVA": "TOURNAMENT",
    "Maç ·": "Matches ·",
    "Gol": "Goals",
    "farklı oyuncu": "different players",
    "karşısında final galibiyeti": "won the final against",
    "Finalist": "Runner-up",
    "Sıra": "Place",
    "maç": "matches",
    "gol": "goals",
    "LEGACY": "LEGACY",
    "FIFA 1–8 Turnuva Arşivi": "FIFA 1–8 Tournament Archive",
    "Yüklediğin Excel arşivinden alınan 382 maç, sekiz final ve tüm zamanlar kayıtları.": "382 matches, eight finals and all-time records imported from the uploaded Excel archive.",
    "Arşivlenen Maç": "Archived Matches",
    "Takım ve skor detayları": "Team and score details",
    "Turnuvalar": "Tournaments",
    "Şampiyonlar": "Champions",
    "Tüm Maçlar": "All Matches",
    "Aşama": "Stage",
    "Ev Sahibi": "Home Player",
    "Deplasman": "Away Player",
    "Skor": "Score",
    "Tüm zamanlar puan liderleri.": "All-time points leaders.",
    "Yedekleme İşlemleri": "Backup Operations",
    "Yedeği İndir": "Download Backup",
    "Maç Sonuçlarını İndir": "Download Match Results",
    "Oyuncuları İndir": "Download Players",
    "Yedeği Geri Yükle": "Restore Backup",
    "JSON Dosyası Seç": "Select JSON File",
    "FIFA 9 Verisini Sıfırla": "Reset FIFA 9 Data",
    "Geçmiş FIFA 1–8 arşivine dokunmadan yalnızca güncel turnuvayı siler.": "Deletes only the current tournament without changing the FIFA 1–8 archive.",
    "Güncel Turnuvayı Sıfırla": "Reset Current Tournament",
    "Kaynak Arşiv": "Source Archive",
    "FIFA 1–8 verileri “All Time Tournament Results.xlsx” dosyasından siteye işlendi.": "FIFA 1–8 data was imported into the site from “All Time Tournament Results.xlsx”.",
    "Arşivi Görüntüle": "View Archive",
    "Teknik Durum": "Technical Status",
    "Canlı site bağlantısı ve erişim modeli.": "Live-site connection and access model.",
    "Ortak canlı veri": "Shared live data",
    "Supabase veritabanı ve Realtime bağlantısı aktif.": "Supabase database and Realtime connection are active.",
    "Supabase bağlantı bilgileri bekleniyor.": "Waiting for Supabase connection details.",
    "Erişim seviyesi": "Access level",
    "Yönetici: sonuç, oyuncu ve aşama yönetimi açık.": "Administrator: results, players and stages can be managed.",
    "İzleyici: bütün veriler görünür, değişiklik kapalı.": "Viewer: all data is visible; editing is disabled.",
    "Telefona eklenebilir": "Can be installed on a phone",
    "HTTPS üzerinden yayınlandığında ana ekrana uygulama gibi eklenebilir.": "When published over HTTPS, it can be added to the home screen like an app.",
    "Maç Sonucu": "Match Result",
    "Ev Sahibi Takımı": "Home Team",
    "Deplasman Takımı": "Away Team",
    "Ev Sahibi Skoru": "Home Score",
    "Deplasman Skoru": "Away Score",
    "Uzatma / Penaltı Galibi": "Extra-time / Penalty Winner",
    "Skor eşit değil / seçilmedi": "Score not level / not selected",
    "Maç Notu": "Match Note",
    "İsteğe bağlı kısa not": "Optional short note",
    "Sonucu Temizle": "Clear Result",
    "İptal": "Cancel",
    "Sonucu Kaydet": "Save Result",
    "Geçerli bir skor gir.": "Enter a valid score.",
    "Berabere biten eleme maçında uzatma/penaltı galibini seç.": "Select the extra-time/penalty winner for a tied knockout match.",
    "Sonuç kaydedildi.": "Result saved.",
    "Sonuç temizlendi.": "Result cleared.",
    "League Phase kurası oluşturuldu: 6 tur, 48 maç.": "League Phase draw generated: 6 rounds, 48 matches.",
    "League Phase tamamlanmadan ikinci aşama oluşturulamaz.": "The second stage cannot be generated before the League Phase is complete.",
    "Altın ve Gümüş grupları oluşturuldu. League Phase puanları taşındı.": "Gold and Silver groups generated. League Phase points were carried over.",
    "İkinci aşama tamamlanmadan eleme serileri oluşturulamaz.": "Knockout series cannot be generated before the second stage is complete.",
    "Eleme serileri oluşturuldu.": "Knockout series generated.",
    "16 oyuncunun tamamını benzersiz isimlerle doldur.": "Enter unique names for all 16 players.",
    "İsimleri Toplu Ekle": "Add Names in Bulk",
    "Her satıra bir oyuncu adı yaz veya yapıştır.": "Enter or paste one player name per line.",
    "İlk 16 dolu satır alınır. Mevcut isimler değiştirilir.": "The first 16 non-empty lines are used. Existing names will be replaced.",
    "İsimleri Uygula": "Apply Names",
    "oyuncu adı uygulandı.": "player names applied.",
    "Değişiklikler bu cihazda kaydedildi.": "Changes were saved on this device.",
    "Değişiklikler canlı siteye kaydedildi.": "Changes were saved to the live site.",
    "Bulut kaydı başarısız. İnternet bağlantısını ve yetkini kontrol et.": "Cloud save failed. Check your internet connection and permissions.",
    "Canlı turnuva verisi güncellendi.": "Live tournament data updated.",
    "Canlı veriye bağlanılamadı. Son kayıtlı görünüm gösteriliyor.": "Could not connect to live data. Showing the most recently saved view.",
    "Bu işlem yalnızca turnuva yöneticisine açıktır.": "This action is restricted to the tournament administrator.",
    "Yönetici oturumu kapatıldı.": "Administrator signed out.",
    "Maç sonuçları CSV olarak indirildi.": "Match results downloaded as CSV.",
    "Yedek yükleme yalnızca yöneticiye açıktır.": "Backup restore is restricted to the administrator.",
    "Geçersiz yedek": "Invalid backup",
    "Yedek başarıyla geri yüklendi.": "Backup restored successfully.",
    "JSON yedeği okunamadı.": "The JSON backup could not be read.",
    "Katılımcılar giriş yapmadan canlı turnuvayı izler. Bu giriş yalnızca sonuç ve fikstür yönetimi içindir.": "Participants can follow the live tournament without signing in. This login is only for result and fixture management.",
    "E-posta": "Email",
    "Parola": "Password",
    "Giriş Yap": "Sign In",
    "Yönetici girişi başarılı.": "Administrator login successful.",
    "Giriş başarısız.": "Login failed.",
    "Bu hesap turnuva yöneticisi olarak yetkilendirilmemiş.": "This account is not authorised as a tournament administrator.",
    "Canlı Site Kurulumu": "Live Site Setup",
    "Bu paket canlı kullanıma hazırdır. Supabase proje URL'si ve anon/public key'i cloud-config.js dosyasına girilmelidir.": "This package is ready for live use. Enter the Supabase Project URL and anon/public key in cloud-config.js.",
    "Supabase projesi oluştur": "Create a Supabase project",
    "SQL Editor'da supabase/schema.sql dosyasını çalıştır.": "Run supabase/schema.sql in the SQL Editor.",
    "Yönetici kullanıcısını ekle": "Add the administrator user",
    "Authentication > Users bölümünden kullanıcı oluştur, UUID'sini tournament_admins tablosuna ekle.": "Create a user under Authentication > Users and add the UUID to the tournament_admins table.",
    "Bağlantı bilgilerini gir": "Enter connection details",
    "Project URL ve anon/public key'i cloud-config.js içine yapıştır.": "Paste the Project URL and anon/public key into cloud-config.js.",
    "Vercel'e yükle": "Deploy to Vercel",
    "Klasörü veya ZIP'i Vercel Drop'a sürükleyip yayınla.": "Drag the folder or ZIP into Vercel Drop and deploy it.",
    "Tamam": "Done",
    "Bu işlem güncel turnuvadaki oyuncuları, fikstürleri ve sonuçları siler. FIFA 1–8 arşivi etkilenmez.": "This deletes the players, fixtures and results in the current tournament. The FIFA 1–8 archive is not affected.",
    "Vazgeç": "Cancel",
    "Evet, Sıfırla": "Yes, Reset",
    "Güncel turnuva sıfırlandı.": "Current tournament reset.",
    "Tüm Zamanlar Merkezi": "All-Time Centre",
    "FIFA 1–8 arşivi ile FIFA 9’da tamamlanan maçların canlı birleşik performans, rekor ve rekabet merkezi. Oyuncu kartları, efsanevi eşleşmeler ve derinlemesine istatistikler tek ekranda.": "The live combined performance, records and rivalry centre for the FIFA 1–8 archive and all completed FIFA 9 matches. Player cards, legendary matchups and deep statistical insights are all on one screen.",
    "Kayıtlı Oyuncu": "Recorded Players",
    "Tüm turnuvalarda yer alan oyuncular": "Players who appeared across all tournaments",
    "FIFA 1–9 birleşik maç verisi": "Combined match data from FIFA 1–9",
    "Tarihî ve canlı turnuva golleri": "Historical and live tournament goals",
    "Aktif Rekabet": "Active Rivalries",
    "En az bir kez karşılaşmış eşleşme": "Matchups that met at least once",
    "Oyuncu Kartları": "Player Cards",
    "Tüm zamanlar yıldızları. Bir karta tıklayarak oyuncu panelini anında değiştir.": "The all-time stars. Click a card to switch the player panel instantly.",
    "Rekorlar Odası": "Records Room",
    "Kupalar, üretkenlik ve üstünlük kayıtları.": "Records for trophies, productivity and dominance.",
    "En Çok Şampiyonluk": "Most Titles",
    "En Çok Final": "Most Finals",
    "En Çok Galibiyet": "Most Wins",
    "En Çok Gol": "Most Goals",
    "En İyi PPG": "Best PPG",
    "En Sağlam Savunma": "Best Defence",
    "En Farklı Galibiyet": "Biggest Win",
    "En Çok Oynanan Rekabet": "Most Played Rivalry",
    "Kayıt oluşmadı.": "No record yet.",
    "Şampiyonlar Kulübü": "Champions Club",
    "Kupaya uzanan oyuncuların özeti.": "A summary of the players who reached the trophy.",
    "Puan Gücü": "Points Power",
    "Tüm zamanlar puan liderleri ve güç eğrisi.": "All-time points leaders and power curve.",
    "En Çok Maç": "Most Matches",
    "En Çok Gol Farkı": "Best Goal Difference",
    "En Yüksek Galibiyet Oranı": "Highest Win Rate",
    "En Çok Clean Sheet": "Most Clean Sheets",
    "Oyuncu Derin Analizi": "Deep Player Analysis",
    "Seçtiğin oyuncunun tüm zamanlar karnesi ve rakip bazlı üstünlükleri.": "The all-time report card and opponent-based dominance profile of the selected player.",
    "Oyuncu Seç": "Select Player",
    "Rekabet Merkezi": "Rivalry Centre",
    "Kimin kime karşı ne kadar üstün olduğunu canlı karşılaştır.": "Compare live who holds the edge over whom.",
    "Oyuncu A": "Player A",
    "Oyuncu B": "Player B",
    "Seçilen oyuncular arasında henüz maç bulunmuyor.": "There are no matches yet between the selected players.",
    "Gol Dengesi": "Goal Balance",
    "Üstünlük": "Edge",
    "En farklı maç": "Biggest result",
    "Maç Geçmişi": "Match History",
    "Berabere": "Draw",
    "En Farklı Galibiyetler": "Biggest Victories",
    "Turnuva tarihinin en ağır skorları.": "The heaviest scorelines in tournament history.",
    "En Çok Karşılaşılan Eşleşmeler": "Most Frequent Matchups",
    "İzleyiciler için hızlı rekabet özeti. Bir satıra tıklayarak rekabet panelini doldur.": "A quick rivalry overview for viewers. Click a row to populate the rivalry panel.",
    "Tüm Zamanlar Verisi Hazır Değil": "All-Time Data Not Ready",
    "Arşiv ve güncel turnuva maçları yüklendiğinde burada detaylı istatistikler görünecek.": "Detailed statistics will appear here once the archive and current tournament matches are loaded.",
    "Rakip Karnesi": "Opponent Record",
    "Henüz rakip verisi oluşmadı.": "No opponent data yet.",
    "Çıktı Merkezi": "Print Centre",
    "Kura ve fikstür verilerini otomatik olarak baskıya hazır maç föylerine dönüştür. Oyun masasına asılacak A3 panodan tur bazlı skor kâğıtlarına kadar bütün dokümanlar mevcut canlı veriden üretilir.": "Automatically convert draw and fixture data into print-ready match sheets. Every document, from the A3 match-table board to round-by-round score sheets, is generated from the current live data.",
    "Önce kura çekilmelidir": "The draw must be completed first",
    "İkinci Aşama": "Second Stage",
    "Altın + Gümüş grupları": "Gold + Silver groups",
    "League Phase tamamlanmalıdır": "The League Phase must be completed",
    "Eleme Serileri": "Knockout Series",
    "Çeyrek final, yarı final ve final": "Quarter-finals, semi-finals and final",
    "İkinci aşama tamamlanmalıdır": "The second stage must be completed",
    "Hazır Paket": "Ready Pack",
    "Baskıya hazır turnuva bölümü": "Tournament sections ready to print",
    "Çıktılar yeni bir sekmede açılır. Tarayıcı yazdırma ekranından Yazdır veya PDF olarak kaydet seçebilirsin. A3 pano için kâğıt boyutunu A3 ve yönü yatay seç.": "Printouts open in a new tab. Use the browser print dialog to print or save as PDF. For the A3 board, select A3 paper and landscape orientation.",
    "League Phase Çıktıları": "League Phase Printouts",
    "Oyun Masası Duvar Panosu": "Match Table Wall Board",
    "16 oyuncu, altı tur ve 48 maçın tamamını tek, geniş turnuva panosunda gösterir.": "Displays all 16 players, six rounds and 48 matches on one wide tournament board.",
    "League Phase Ana Skor Föyü": "League Phase Master Score Sheet",
    "Bütün maçları; oynandı, siteye girildi ve doğrulandı kutularıyla kompakt kontrol tablosunda toplar.": "Collects every match in a compact control table with played, entered on site and verified boxes.",
    "Tur Bazlı Maç Föyleri": "Round-by-Round Match Sheets",
    "Her tur için ayrı sayfa. Büyük skor kutuları, takım alanları, tarih ve sonucu yazan kişi bölümü içerir.": "A separate page for each round with large score boxes, team fields, date and recorded-by sections.",
    "Manuel Puan Tablosu": "Manual Standings Sheet",
    "Oyuncu isimleri önceden yazılı, elle güncellenebilir O-G-B-M-AG-YG-AV-P çalışma tablosu.": "A manual MP-W-D-L-GF-GA-GD-Pts worksheet with player names prefilled.",
    "İkinci Aşama ve Eleme Çıktıları": "Second Stage and Knockout Printouts",
    "Altın Grup Maç Paketi": "Gold Group Match Pack",
    "Beş turluk fikstür, skor föyleri ve kümülatif puan tablosu.": "Five-round schedule, score sheets and cumulative standings.",
    "Gümüş Grup Maç Paketi": "Silver Group Match Pack",
    "Eleme Serileri Panosu": "Knockout Series Board",
    "Üç çeyrek final serisi, iki yarı final ve tek maçlık final için skor kayıt alanları.": "Score-recording fields for three quarter-final series, two semi-finals and the single-match final.",
    "Mevcut Tam Turnuva Paketi": "Current Full Tournament Pack",
    "Şu anda oluşturulmuş bütün aşamaları tek baskı dokümanında birleştirir.": "Combines every currently generated stage into one print document.",
    "Çıktıyı Aç": "Open Printout",
    "Aşama Bekleniyor": "Stage Pending",
    "Fiziksel Skor Kontrol Sistemi": "Physical Score Control System",
    "Sen gemide veya oyun alanında olmadığında kullanılacak standart.": "The standard to use when you are away from the vessel or playing area.",
    "Maç oynandıktan sonra skor yazılır": "Record the score after the match",
    "Her iki oyuncu skoru kontrol eder; beraberlik veya penaltı bilgisi not alanına eklenir.": "Both players verify the score; draw or penalty details are added to the notes field.",
    "“Oynandı” kutusu işaretlenir": "Tick the Played box",
    "Maçın fiziksel kaydı tamamlanır ve sonuç kâğıdı oyun masasında bırakılır.": "The physical record is completed and the result sheet remains at the match table.",
    "Sonuç website'e girilir": "Enter the result on the website",
    "Yönetici sonucu sisteme kaydettikten sonra “Site” kutusunu işaretler.": "After the administrator saves the result, the Site box is ticked.",
    "Doğrulama tamamlanır": "Complete verification",
    "Fiziksel kâğıt ile canlı site aynıysa “Doğrulandı” kutusu işaretlenir.": "Tick Verified when the paper sheet and live website match.",
    "Canlı Bağlantı": "Live Link",
    "Baskı başlığında yer alacak web adresi.": "The website address displayed in the print header.",
    "Kâğıdın üst kısmında turnuva adı, baskı tarihi, edisyon, canlı site adresi ve sonuç sorumlusu alanı otomatik yer alır.": "The header automatically includes the tournament name, print date, edition, live website and result recorder fields.",
    "Hazır": "Ready",
    "Bekliyor": "Pending",
    "Çok Sayfalı PDF": "Multi-page PDF",
    "6 Sayfa · A4": "6 Pages · A4",
    "A4 · Dikey": "A4 · Portrait",
    "A4 · Yatay": "A4 · Landscape",
    "A3 · Yatay": "A3 · Landscape",
    "Takım İstatistikleri": "Team Statistics",
    "Takım Verisi Hazır Değil": "Team Data Not Ready",
    "Maç sonuçlarında takım adları kaydedildiğinde takım istatistikleri burada otomatik oluşacak.": "Team statistics will be generated automatically here once team names are saved with match results.",
    "Takım İstatistikleri Merkezi": "Team Statistics Centre",
    "Hangi takımın kaç kez seçildiği, takım bazlı puan durumu ve her oyuncunun kullandığı takımlardaki performansı. FIFA 1–8 arşivi ile FIFA 9 canlı sonuçları birlikte hesaplanır.": "See how often each team was selected, team-based standings and every player's performance with the teams they used. The FIFA 1–8 archive and live FIFA 9 results are calculated together.",
    "En Çok Seçilen Takım": "Most Selected Team",
    "Takım Puan Lideri": "Team Points Leader",
    "En İyi Takım PPG": "Best Team PPG",
    "En Çok Gol Atan Takım": "Top-Scoring Team",
    "Takım verisi bekleniyor": "Awaiting team data",
    "En Çok Tercih Edilen Takımlar": "Most Selected Teams",
    "Takım seçimi bir maçtaki her oyuncu tarafı için bir kullanım olarak sayılır. Yazım varyasyonları standardize edilmiştir.": "A team selection is counted once for each player side in a match. Naming variations have been standardised.",
    "Takım Bazlı Puan Durumu": "Team-Based Standings",
    "Bütün oyuncuların aynı takımla aldığı sonuçlar birleştirilir: galibiyet 3, beraberlik 1 puan.": "Results achieved by all players with the same team are combined: 3 points for a win and 1 for a draw.",
    "Takım Güç Endeksi": "Team Power Index",
    "Seçim sayısı, puan ve maç başı performans dengesi.": "A balance of selection count, points and per-match performance.",
    "En İyi Galibiyet Oranı": "Best Win Rate",
    "En İyi Averaj": "Best Goal Difference",
    "En Geniş Oyuncu Kitlesi": "Widest Player Reach",
    "Takım Derin Analizi": "Deep Team Analysis",
    "Seçilen takımın toplam karnesi ve oyunculara göre katkı dağılımı.": "The selected team's total record and contribution breakdown by player.",
    "Takım Seç": "Select Team",
    "Oyuncu–Takım Performansı": "Player–Team Performance",
    "Bir oyuncunun hangi takımlarla oynadığını ve her takımla elde ettiği sonuçları incele.": "Review which teams a player used and the results achieved with each team.",
    "Oyuncuların Takım Tercihleri": "Players' Team Preferences",
    "Her oyuncunun en çok kullandığı takım ve en verimli takım tercihi.": "Each player's most-used team and most efficient team choice.",
    "Seçim": "Selections",
    "Takım Seçimi": "Team Selections",
    "Farklı Takım": "Different Teams",
    "En Çok Kullandığı": "Most Used",
    "En Verimli Takımı": "Most Efficient Team",
    "En Çok Kullanan": "Most Frequent User",
    "En Çok Puan Kazandıran": "Top Points Contributor",
    "En Verimli Oyuncu": "Most Efficient Player",
    "Oyuncu Katkısı": "Player Contribution",
    "Oyuncu katkı verisi bulunmuyor.": "No player contribution data is available.",
    "En Çok Kullandığı Takım": "Most-Used Team",
    "En Çok Galibiyet Aldığı": "Most Wins With",
    "En Çok Gol Attığı": "Most Goals With",
    "Takım Bazlı Kariyer Karnesi": "Team-Based Career Record",
    "Bu oyuncu için takım verisi bulunmuyor.": "No team data is available for this player.",
    "Atılan Gol": "Goals For",
    "Yenilen Gol": "Goals Against",
    "Gol / Maç": "Goals / Match",
    "Yenilen / Maç": "Conceded / Match",
    "Takım": "Team",
    "Oyuncu": "Player",
    "Canlı İstatistikler": "Live Statistics",
    "Canlı İstatistikler Kura Sonrası Başlar": "Live Statistics Start After the Draw",
    "16 oyuncu kaydedilip League Phase fikstürü oluşturulduğunda FIFA 9 canlı istatistik merkezi otomatik devreye girecek.": "The FIFA 9 live statistics centre will activate automatically after 16 players are registered and the League Phase schedule is generated.",
    "Canlı Turnuva İstatistikleri": "Live Tournament Statistics",
    "FIFA 9 oynanırken girilen her skorla anında yenilenen oyuncu performansları, rekorlar, takım tercihleri, form grafikleri ve rekabet verileri.": "Player performances, records, team selections, form charts and rivalry data update instantly with every FIFA 9 score entered.",
    "Canlı Statsı Paylaş": "Share Live Stats",
    "Puan Durumuna Git": "Open Standings",
    "Turnuva Verisi": "Tournament Data",
    "Canlı Güncelleme Aktif": "Live Updates Active",
    "Son veri:": "Latest data:",
    "kayıtlı fikstür": "recorded fixtures",
    "Tamamlanan Maç": "Completed Matches",
    "aktif fikstür": "active fixtures",
    "Performans Lideri": "Performance Leader",
    "performans puanı": "performance points",
    "Gol Lideri": "Goals Leader",
    "Canlı Rekor Panosu": "Live Records Board",
    "Yalnızca FIFA 9’da tamamlanan maçlardan hesaplanır ve her skor girişinde değişebilir.": "Calculated only from completed FIFA 9 matches and may change after every result.",
    "En İyi Hücum": "Best Attack",
    "En Formda Oyuncu": "In-Form Player",
    "Galibiyet Serisi": "Winning Streak",
    "En Gollü Maç": "Highest-Scoring Match",
    "Sonuç bekleniyor": "Awaiting results",
    "Takım verisi bekleniyor": "Awaiting team data",
    "Turnuva Nabzı": "Tournament Pulse",
    "Her aşamanın maç, gol ve tamamlanma durumu.": "Match, goal and completion status for every stage.",
    "FIFA 9 Oyuncu Performans Kartları": "FIFA 9 Player Performance Cards",
    "Lig, Altın/Gümüş ve eleme maçlarının canlı birleşik performansı. Bu tablo resmî grup sıralamasından ayrı bir istatistik görünümüdür.": "Live combined performance across league, Gold/Silver and knockout matches. This is a statistical view separate from the official group standings.",
    "Canlı Performans Tablosu": "Live Performance Table",
    "Bütün FIFA 9 maçları üzerinden W/D/L, gol, performans puanı ve form.": "W/D/L, goals, performance points and form across all FIFA 9 matches.",
    "Form ve Seri Merkezi": "Form and Streak Centre",
    "Son beş maç, güncel galibiyet ve yenilmezlik serileri.": "Last five matches, current winning and unbeaten streaks.",
    "Son Tamamlanan Maçlar": "Latest Completed Matches",
    "Skor giriş zamanına göre en güncel sonuçlar.": "The latest results ordered by score-entry time.",
    "Sıradaki Maçlar": "Upcoming Matches",
    "Henüz sonucu girilmemiş yaklaşan fikstürler.": "Upcoming fixtures whose results have not yet been entered.",
    "FIFA 9 Rekabetleri": "FIFA 9 Rivalries",
    "Bu turnuvada en çok karşılaşan oyuncular ve güncel üstünlük dengesi.": "The most frequent matchups and current balance of power in this tournament.",
    "Canlı Takım Tercihleri": "Live Team Selections",
    "Yalnızca FIFA 9’da seçilen takımların kullanım ve başarı özeti.": "Usage and performance summary for teams selected only in FIFA 9.",
    "Galibiyet Serisi": "Winning Streak",
    "Yenilmezlik": "Unbeaten",
    "Henüz tamamlanan maç yok.": "No completed matches yet.",
    "Şu anda bekleyen fikstür yok.": "There are no pending fixtures at the moment.",
    "Takım bekleniyor": "Team pending",
    "Kazanan:": "Winner:",
    "Bu turnuvada henüz tekrar eden bir eşleşme oluşmadı.": "No repeated matchup has occurred in this tournament yet.",
    "Takım isimleri maç sonuçlarına girildiğinde canlı takım istatistikleri burada oluşacak.": "Live team statistics will appear here once team names are entered with match results.",
    "Denge": "Level",
    "Büyük Final": "Grand Final",
    "Eleme Serileri": "Knockout Series",
    "Perf P": "Perf Pts",
    "FIFA 9 · CANLI TURNUVA STATS": "FIFA 9 · LIVE TOURNAMENT STATS",
    "Canlı Maç": "Live Match",
    "Canlı Maç Merkezi": "Live Match Centre",
    "Bir fikstürü canlı yayına al; dakikayı, skoru ve maç olaylarını anlık güncelle. İzleyiciler aynı ekranı Supabase üzerinden eşzamanlı takip eder.": "Take a fixture live and update the minute, score and match events in real time. Viewers follow the same screen simultaneously through Supabase.",
    "Şu anda canlı maç yok": "There is no live match right now",
    "oynanmamış fikstür canlı yayına hazır.": "unplayed fixtures are ready to go live.",
    "Canlı Yayına Hazır Maçlar": "Matches Ready to Go Live",
    "Yönetici olarak bir maçı seçip canlı skor takibini başlat.": "Select a match as administrator and start live score tracking.",
    "Nasıl Çalışır?": "How It Works",
    "Canlı maç yönetim akışı.": "Live match management flow.",
    "Maçı seç ve yayını başlat": "Select the match and start the broadcast",
    "Takım adlarını gir; skor 0–0 ve dakika 0 olarak başlar.": "Enter the team names; the score starts at 0–0 and the minute at 0.",
    "Dakika ve skoru güncelle": "Update the minute and score",
    "+1 / +5 dakika kontrolleri, hızlı gol düğmeleri ve olay zaman çizelgesi.": "+1 / +5 minute controls, quick goal buttons and an event timeline.",
    "İzleyiciler canlı takip eder": "Viewers follow live",
    "Her kayıt Supabase Realtime ile açık telefon ve bilgisayarlara aktarılır.": "Every update is delivered to open phones and computers through Supabase Realtime.",
    "Maç sonunda fikstüre işle": "Post the result to the fixture at full time",
    "Final skor, takımlar ve gerekiyorsa penaltı galibi tek tuşla kaydedilir.": "The final score, teams and penalty winner when required are saved with one action.",
    "İzleyici modundasın. Canlı yayın başlatma ve skor yönetimi yalnızca turnuva yöneticisine açıktır.": "You are in viewer mode. Starting a live broadcast and managing the score are restricted to the tournament administrator.",
    "Son Canlı Yayınlar": "Recent Live Broadcasts",
    "Canlı takip üzerinden tamamlanan son maçlar.": "The latest matches completed through live tracking.",
    "Canlı Yayını Başlat": "Start Live Broadcast",
    "YÖNETİCİ BEKLENİYOR": "AWAITING ADMIN",
    "Takım bekleniyor": "Awaiting team",
    "EV SAHİBİ": "HOME",
    "DEPLASMAN": "AWAY",
    "CANLI": "LIVE",
    "DURAKLATILDI": "PAUSED",
    "DEVRE ARASI": "HALF-TIME",
    "İKİNCİ YARI": "SECOND HALF",
    "UZATMA": "EXTRA TIME",
    "PENALTILAR": "PENALTIES",
    "MAÇ SONU": "FULL TIME",
    "Canlı Kontrol Masası": "Live Control Desk",
    "Dakika, maç durumu, takım ve skor yönetimi.": "Minute, match status, team and score management.",
    "Dakika": "Minute",
    "Ek Süre": "Added Time",
    "Canlı": "Live",
    "Duraklat": "Pause",
    "Devre Arası": "Half-Time",
    "2. Yarı": "Second Half",
    "Uzatma": "Extra Time",
    "Canlı Skoru Paylaş": "Share Live Score",
    "Yayını İptal Et": "Cancel Broadcast",
    "Maçı Bitir ve Kaydet": "Finish and Save Match",
    "Maç Olayı Ekle": "Add Match Event",
    "Gol, kart veya önemli notu dakika bilgisiyle kaydet.": "Record a goal, card or important note with the match minute.",
    "Olay": "Event",
    "Gol": "Goal",
    "Sarı Kart": "Yellow Card",
    "Kırmızı Kart": "Red Card",
    "Maç Notu": "Match Note",
    "Taraf": "Side",
    "Genel": "General",
    "Açıklama": "Description",
    "Olayı Canlı Yayına Ekle": "Add Event to Live Broadcast",
    "Canlı yayın aktif": "Live broadcast active",
    "Skor, dakika ve maç olayları yönetici tarafından güncellendikçe bu ekran otomatik yenilenir.": "This screen refreshes automatically as the administrator updates the score, minute and match events.",
    "Canlı Maç Zaman Çizelgesi": "Live Match Timeline",
    "En yeni olay üstte gösterilir.": "The newest event is shown first.",
    "Henüz maç olayı eklenmedi. Skor ve dakika canlı olarak takip ediliyor.": "No match event has been added yet. The score and minute are being tracked live.",
    "Skor güncellendi": "Score updated",
    "Canlı maç olayı": "Live match event",
    "Önce aktif canlı maçı bitir veya iptal et.": "Finish or cancel the active live match first.",
    "Bu maç canlı yayına uygun değil.": "This match is not eligible for live broadcasting.",
    "Canlı maç yayını başlatıldı.": "Live match broadcast started.",
    "Maç olayı canlı yayına eklendi.": "Match event added to the live broadcast.",
    "Canlı Maçı Bitir": "Finish Live Match",
    "Canlı skor fikstüre resmî maç sonucu olarak işlenecek. Bu işlem puan tablolarını ve tüm istatistikleri otomatik günceller.": "The live score will be posted as the official fixture result. This automatically updates standings and all statistics.",
    "Uzatma / Penaltı Galibi": "Extra-Time / Penalty Winner",
    "Kazananı seç": "Select the winner",
    "Maç Sonu Notu": "Full-Time Note",
    "Canlı Maç Merkezi üzerinden tamamlandı": "Completed through the Live Match Centre",
    "Skoru Kaydet ve Yayını Bitir": "Save Score and End Broadcast",
    "Eleme maçında kazanan oyuncuyu seç.": "Select the winning player in the knockout match.",
    "Canlı maç tamamlandı ve fikstüre işlendi.": "Live match completed and posted to the fixture.",
    "Canlı Yayını İptal Et": "Cancel Live Broadcast",
    "Canlı skor ve zaman çizelgesi silinecek; fikstürde resmî sonuç oluşmayacak.": "The live score and timeline will be deleted; no official fixture result will be created.",
    "Yayını İptal Et": "Cancel Broadcast",
    "Canlı yayın iptal edildi.": "Live broadcast cancelled.",
    "Canlı Maçı Aç →": "Open Live Match →",
    "Şu anda canlı maç yok": "No live match right now",
    "Form Merkezi": "Form Centre",
    "Form Verisi Hazır Değil": "Form Data Not Ready",
    "Oyuncuların maç geçmişi oluştuğunda Son 20 Maç Form Merkezi otomatik olarak çalışacak.": "The Last 20 Match Form Centre will activate automatically once player match histories are available.",
    "Oyuncuları Aç": "Open Players",
    "Form Tablosunu Paylaş": "Share Form Table",
    "Canlı İstatistiklere Git": "Go to Live Statistics",
    "Form Gücü": "Form Power",
    "Analiz Penceresi": "Analysis Window",
    "Son 5, 10 veya 20 maçlık güncel görünüm.": "Current view for the last 5, 10 or 20 matches.",
    "Form analiz penceresi": "Form analysis window",
    "Son 5": "Last 5",
    "Son 10": "Last 10",
    "Son 20": "Last 20",
    "Oyuncu Havuzu": "Player Pool",
    "FIFA 9 kadrosunu veya arşivdeki bütün oyuncuları karşılaştır.": "Compare the FIFA 9 squad or every player in the archive.",
    "Oyuncu havuzu": "Player pool",
    "FIFA 9 Kadrosu": "FIFA 9 Squad",
    "Tüm Oyuncular": "All Players",
    "Son 5'in En İyisi": "Best Over Last 5",
    "Aktif Yenilmezlik": "Active Unbeaten Run",
    "En Büyük Yükseliş": "Biggest Rise",
    "Form Güç Kartları": "Form Power Cards",
    "Momentum Sıralaması": "Momentum Ranking",
    "Son 5 maç ile önceki 5 maç arasındaki puan farkı.": "Points difference between the last five matches and the previous five.",
    "Form Gücü:": "Form Power:",
    "PPG %70, son 5 maç %20 ve maç başı averaj %10 ağırlıkla 100 üzerinden hesaplanır.": "Calculated out of 100 using 70% PPG, 20% last-five performance and 10% goal difference per match.",
    "Oyuncu Form Dosyası": "Player Form File",
    "Seçilen oyuncunun maç maç form şeridi, seri durumu ve rakip detayları.": "Match-by-match form strip, streak status and opponent details for the selected player.",
    "Form Rekorları": "Form Records",
    "Seçili maç penceresinin öne çıkan performansları.": "Standout performances in the selected match window.",
    "En Çok Puan": "Most Points",
    "En İyi Hücum": "Best Attack",
    "En İyi Averaj": "Best Goal Difference",
    "Galibiyet Serisi": "Winning Streak",
    "En Yüksek G%": "Highest Win Rate",
    "Form Haritası": "Form Map",
    "Her satırda en eski maç solda, en güncel maç sağda.": "The oldest match is on the left and the latest match is on the right in every row.",
    "Önceki 5": "Previous 5",
    "Yükselişte": "Rising",
    "Düşüşte": "Declining",
    "Dengeli": "Stable",
    "Oyuncu Form Dosyası": "Player Form File",
    "Aktif Seri": "Active Streak",
    "Yenilmezlik": "Unbeaten Run",
    "En Çok Kullanılan Takım": "Most Used Team",
    "Maç Maç Form Çizgisi": "Match-by-Match Form Line",
    "Edisyon": "Edition",
    "Rakip": "Opponent",
    "Sonuç": "Result",
    "Henüz maç geçmişi yok.": "No match history yet.",
    "Maç yok": "No match",
    "Maç verisi bekleniyor": "Waiting for match data",
    "Takım verisi yok": "No team data",
    "Sohbet": "Chat",
    "Turnuva Sohbeti": "Tournament Chat",
    "Sohbet özelliği için canlı Supabase bağlantısı gereklidir.": "A live Supabase connection is required for chat.",
    "Kayıtlı oyuncular için gerçek zamanlı genel sohbet ve canlı maç odası.": "Real-time general chat and live-match room for registered players.",
    "Sohbet Hesabını Oluştur": "Create Your Chat Account",
    "İsmini yazmana gerek yok. Turnuva kadrosundan kendi adını seç ve yalnızca sana ait bir PIN belirle.": "You do not need to type your name. Select your registered name from the tournament roster and create a personal PIN.",
    "Kayıtlı Oyuncu": "Registered Player",
    "Oyuncunu seç": "Select your player",
    "kayıtlı": "registered",
    "4–8 Haneli PIN": "4–8 Digit PIN",
    "Hazırlanıyor...": "Preparing...",
    "Sohbete Katıl": "Join Chat",
    "Önce turnuva oyuncuları kaydedilmelidir.": "Tournament players must be registered first.",
    "Nasıl Çalışır?": "How Does It Work?",
    "Hızlı, isim hatasız ve turnuva kadrosuna bağlı.": "Fast, typo-free and linked to the official roster.",
    "Kayıtlı oyuncu adını listeden seç.": "Select your registered player name from the list.",
    "Kişisel PIN kodunu oluştur. Aynı adı başka cihazda açmak için bu PIN kullanılır.": "Create a personal PIN. Use it to recover the same name on another device.",
    "Genel sohbeti ve canlı maç sohbetini anlık takip et.": "Follow the general chat and live-match chat in real time.",
    "PIN kodunu unutursan turnuva yöneticisi hesabını sıfırlayabilir.": "If you forget your PIN, the tournament administrator can reset your account.",
    "Genel Sohbet": "General Chat",
    "çevrimiçi": "online",
    "Çevrimiçi oyuncular burada görünür.": "Online players appear here.",
    "Mesajlar yükleniyor...": "Loading messages...",
    "İlk mesajı sen gönder": "Send the first message",
    "Turnuva sohbeti burada başlayacak.": "The tournament conversation starts here.",
    "Mesajı sil": "Delete message",
    "Mesajını yaz...": "Write a message...",
    "Gönder": "Send",
    "Enter: gönder · Shift+Enter: yeni satır": "Enter: send · Shift+Enter: new line",
    "Turnuva kadrosuna doğrulanmış sohbet hesabı": "Chat account verified against the tournament roster",
    "Kanal": "Channel",
    "Genel": "General",
    "Durum": "Status",
    "Çevrimiçi": "Online",
    "Başka bir cihazda aynı oyuncu adını kullanmak için oluşturduğun PIN kodunu gir.": "Enter your PIN to use the same player name on another device.",
    "Sohbet Hesap Yönetimi": "Chat Account Management",
    "PIN unutulan veya yanlış seçilen oyuncu hesaplarını sıfırla.": "Reset accounts with forgotten PINs or incorrect player selection.",
    "KAYITLI": "REGISTERED",
    "Son görülme": "Last seen",
    "Henüz kayıt olmadı": "Not registered yet",
    "Sıfırla": "Reset",
    "Açık": "Available",
    "Canlı bağlantı hazır değil.": "Live connection is not ready.",
    "Anonim giriş açılamadı. Supabase Authentication ayarlarında Anonymous Sign-Ins özelliğini etkinleştir.": "Anonymous sign-in failed. Enable Anonymous Sign-Ins in Supabase Authentication settings.",
    "Sohbet hesabın hazır.": "Your chat account is ready.",
    "Bu oyuncu daha önce kaydedilmiş. Doğru PIN kodunu gir.": "This player is already registered. Enter the correct PIN.",
    "PIN kodu 4–8 rakam olmalıdır.": "The PIN must contain 4–8 digits.",
    "Seçilen oyuncu kayıtlı kadroda bulunamadı.": "The selected player is not available in the registered roster.",
    "Sohbet hesabı oluşturulamadı.": "Chat account could not be created.",
    "Mesaj en fazla 500 karakter olabilir.": "Messages can contain up to 500 characters.",
    "Mesaj gönderilemedi.": "Message could not be sent.",
    "Mesaj silinemedi.": "Message could not be deleted.",
    "Hesap sıfırlanamadı.": "Account could not be reset.",
    "Oyuncunun sohbet hesabı sıfırlandı.": "The player's chat account was reset.",
    "Bugün": "Today",
    "Dün": "Yesterday",
    "Maç Oranları": "Match Odds",
    "Tahmin & Oran Merkezi": "Prediction & Odds Centre",
    "Geçmiş turnuvalar, son 20 maç formu, FIFA 9 güncel performansı ve ikili rekabet verileriyle hesaplanan dinamik 1–X–2 oranları. Her yeni sonuçtan sonra oynanmamış maçlar otomatik yeniden değerlendirilir.": "Dynamic 1–X–2 odds calculated from past tournaments, last-20 form, current FIFA 9 performance and head-to-head data. Unplayed fixtures are reassessed automatically after every new result.",
    "Oranları Paylaş": "Share Odds",
    "Form Merkezine Git": "Go to Form Centre",
    "DİNAMİK MODEL": "DYNAMIC MODEL",
    "Özel turnuva tahmini:": "Private tournament prediction:",
    "Bu oranlar yalnızca eğlence ve istatistiksel karşılaştırma amacıyla üretilir. Gerçek bahis, para yatırma veya ödeme özelliği içermez.": "These odds are generated only for entertainment and statistical comparison. There is no real betting, deposit or payment functionality.",
    "En Güçlü Favori": "Strongest Favourite",
    "En Dengeli Maç": "Most Balanced Match",
    "Beraberlik Sinyali": "Draw Signal",
    "Sürpriz Potansiyeli": "Upset Potential",
    "Fikstür bekleniyor": "Waiting for fixtures",
    "Yaklaşan Maçlar": "Upcoming Matches",
    "Tüm Maçlar": "All Matches",
    "Eleme & Final": "Knockout & Final",
    "Oran fikstürü filtresi": "Odds fixture filter",
    "NET FAVORİ": "CLEAR FAVOURITE",
    "DENGE MAÇI": "BALANCED MATCH",
    "SÜRPRİZ ADAYI": "UPSET WATCH",
    "MODEL AÇIK": "MODEL LIVE",
    "Detaylı Analiz →": "Detailed Analysis →",
    "model skoru": "model score",
    "Veri bekleniyor": "Waiting for data",
    "X · Beraberlik": "X · Draw",
    "Olasılık dağılımı": "Probability distribution",
    "Model favorisi": "Model favourite",
    "İkili rekabet": "Head-to-head",
    "Güven": "Confidence",
    "İlk karşılaşma": "First meeting",
    "Oran Motoru Nasıl Çalışır?": "How Does the Odds Engine Work?",
    "Model şeffaf, deterministik ve her cihazda aynı sonucu üretir.": "The model is transparent, deterministic and produces the same result on every device.",
    "Son 20 maç form gücü": "Last-20 form strength",
    "Son 5 maç performansı": "Last-five performance",
    "Tüm zamanlar verimliliği": "All-time efficiency",
    "FIFA 9 güncel performansı": "Current FIFA 9 performance",
    "Gol ve averaj profili": "Goal and goal-difference profile",
    "Momentum trendi": "Momentum trend",
    "H2H düzeltmesi": "H2H adjustment",
    "İkili rekabet sonucuna göre en fazla ±6 güç puanı": "Up to ±6 strength points based on head-to-head results",
    "Model marjı": "Model margin",
    "%6 gösterim marjı; gerçek bahis marjı değildir": "6% display margin; not a real betting margin",
    "Yeni oyuncu koruması": "New-player protection",
    "Az maçlı oyuncular nötr değere yaklaştırılır; tek sonuç oranı aşırı değiştirmez": "Players with few matches are regressed toward neutral; one result cannot distort the odds excessively",
    "Eleme maçlarında X": "X in knockout matches",
    "Normal süre beraberlik olasılığını ifade eder": "Represents the probability of a draw in regulation time",
    "Maç Oranları Kura Sonrası Başlar": "Match Odds Start After the Draw",
    "Oyuncular kaydedilip fikstür oluşturulduğunda geçmiş sonuçlara dayalı dinamik oran motoru otomatik çalışacak.": "The dynamic odds engine based on historical results will activate automatically after players are registered and the schedule is generated.",
    "Bu maç için güncel oran bulunamadı.": "No current odds were found for this match.",
    "MODEL SKORU": "MODEL SCORE",
    "Model Bileşeni": "Model Component",
    "Üstünlük": "Edge",
    "Denge": "Balanced",
    "FIFA 9 güncel": "Current FIFA 9",
    "Gol profili": "Goal profile",
    "ham güç": "raw strength",
    "Son İkili Karşılaşmalar": "Recent Head-to-Head Meetings",
    "Bu iki oyuncu arasında kayıtlı geçmiş maç bulunmuyor.": "There is no recorded historical match between these players.",
    "Gösterilen oranlar, model olasılıklarına %6 sunum marjı uygulanarak oluşturulur. Gerçek para veya bahis işlevi yoktur.": "The displayed odds are created by applying a 6% presentation margin to model probabilities. There is no real-money or betting functionality.",
    "Bu Maçı Paylaş": "Share This Match",
    "Paylaşılacak oynanmamış maç bulunmuyor.": "There is no unplayed match available to share.",
    "Yalnızca eğlence ve istatistiksel tahmin amaçlıdır; gerçek bahis içermez.": "For entertainment and statistical prediction only; no real betting is involved.",
    "Yüksek veri güveni": "High data confidence",
    "Orta veri güveni": "Medium data confidence",
    "Sınırlı veri güveni": "Limited data confidence",
    "Kayıt oluşmadı.": "No record available.",
    "Tüm hakları saklıdır.": "All rights reserved.",
    "Zekâ Merkezi": "Intelligence Centre",
    "Turnuva Zekâ Merkezi": "Tournament Intelligence Centre",
    "Maç öncesi analizden canlı momentuma, Elo gücünden rekabet DNA’sına, tahmin liginden oyuncu kartlarına kadar bütün veri katmanları tek merkezde.": "All data layers in one centre, from pre-match analysis and live momentum to Elo strength, rivalry DNA, the prediction league and player cards.",
    "Matchday": "Matchday",
    "Tahmin Ligi": "Prediction League",
    "Rozetler": "Achievements",
    "Simülatör": "Simulator",
    "Oyuncu Kartları": "Player Cards",
    "Maç öncesi analiz, canlı hikâye ve maç sonrası otomatik rapor tek akışta.": "Pre-match analysis, live narrative and an automatic post-match report in one flow.",
    "Yaklaşan Maç Dosyaları": "Upcoming Match Files",
    "Otomatik Maç Sonu Hikâyeleri": "Automatic Post-Match Stories",
    "Elo Güç Sıralaması": "Elo Power Ranking",
    "Rakibin gücü, maç sonucu, skor farkı ve turnuva aşamasını dikkate alan uzun vadeli performans modeli.": "A long-term performance model that considers opponent strength, match result, score margin and tournament stage.",
    "Canlı Elo Sıralaması": "Live Elo Ranking",
    "En Hızlı Yükselen": "Fastest Riser",
    "Ortalama Güç": "Average Strength",
    "İşlenen Maç": "Processed Matches",
    "Rekabet Kimliği": "Rivalry Identity",
    "Her eşleşmenin tarihini, psikolojik üstünlüğünü, gol karakterini ve kader anlarını tek kartta çözümler.": "Analyses the history, psychological edge, scoring character and defining moments of every matchup in one card.",
    "Denge Endeksi": "Balance Index",
    "Gol Yoğunluğu": "Goal Intensity",
    "Beraberlik Oranı": "Draw Rate",
    "Psikolojik Üstünlük": "Psychological Edge",
    "Rekabet Zaman Çizelgesi": "Rivalry Timeline",
    "Oyuncu Üzerindeki Etki": "Player Impact",
    "Tahmin Şampiyonası": "Prediction Championship",
    "Oyuncular maç başlamadan skor tahmini yapar. Tam skor, doğru sonuç, gol farkı ve sürpriz tahmin bonuslarıyla ayrı bir şampiyonluk yarışı oluşur.": "Players predict the score before kickoff. Exact score, correct outcome, goal-difference and upset bonuses create a separate championship race.",
    "Tahminini Gönder": "Submit Your Prediction",
    "Tahmin Ligi Puan Durumu": "Prediction League Standings",
    "Tahminlerim": "My Predictions",
    "Tahmini Kaydet / Güncelle": "Save / Update Prediction",
    "Oyuncu oturumu gerekli": "Player Session Required",
    "Sohbetten Oyuncu Girişi Yap": "Sign In Through Chat",
    "Başarımlar & Rozetler": "Achievements & Badges",
    "Sonuçlar, canlı maç olayları, seriler, Elo sürprizleri ve takım uzmanlığından otomatik kazanılan dijital başarımlar.": "Digital achievements automatically unlocked from results, live match events, streaks, Elo upsets and team expertise.",
    "Oyuncu Rozet Vitrini": "Player Badge Showcase",
    "Rozet Kataloğu": "Badge Catalogue",
    "Qualification Simulator": "Qualification Simulator",
    "Olası skorları gir, gerçek turnuva verisini değiştirmeden sıralamanın ve yükselme çizgilerinin nasıl değişeceğini anında gör.": "Enter possible scores and instantly see how the standings and qualification lines change without altering official tournament data.",
    "Skor Senaryoları": "Score Scenarios",
    "Simüle Puan Durumu": "Simulated Standings",
    "Sıralamayı Yeniden Hesapla": "Recalculate Standings",
    "Senaryo Notları": "Scenario Notes",
    "Oyuncu Kimlik Kartları": "Player Identity Cards",
    "Her sonuçtan sonra değişen overall, oyun stili, güçlü yönler, Elo seviyesi, rozetler ve takım uzmanlığı.": "Overall rating, play style, strengths, Elo level, badges and team expertise that change after every result.",
    "Kart Koleksiyonu": "Card Collection",
    "Oyun Stili": "Play Style",
    "Elo Sınıfı": "Elo Tier",
    "İSTİKRAR": "CONSISTENCY",
    "MİRAS": "LEGACY",
    "Senaryo sıralaması yeniden hesaplandı.": "Scenario standings recalculated.",
    "Tahminin kaydedildi.": "Your prediction has been saved.",
    "Önce Sohbet bölümünden oyuncu PIN oturumu aç.": "Open a player PIN session in Chat first.",
    "Bu maç tahmine kapalı.": "Predictions are closed for this match.",
    "Dinamik Turnuva Simülasyonu": "Dynamic Tournament Simulation",
    "Girilen gerçek sonuçları sabitler; kalan League Phase, Altın/Gümüş Grup, eleme serileri, yarı finaller ve finali güncel Elo, son 20 maç formu, momentum, gol profili ve ikili rekabete göre sürekli yeniden oynatır.": "Locks in recorded results and continuously replays the remaining League Phase, Gold/Silver Groups, knockout series, semi-finals and final using current Elo, last-20 form, momentum, scoring profile and head-to-head data.",
    "Simülasyonu Yenile": "Refresh Simulation",
    "Simülasyon Hassasiyeti": "Simulation Precision",
    "Her skor girişinden sonra otomatik yeniden hesaplanır.": "Automatically recalculated after every recorded score.",
    "Şampiyonluk Favorisi": "Title Favourite",
    "En Olası Final": "Most Likely Final",
    "Sürpriz Şampiyon Adayı": "Dark-Horse Champion",
    "En Olası Şampiyon": "Most Likely Champion",
    "Şampiyonluk Olasılığı": "Championship Probability",
    "Model tek bir sonuç söylemez; kalan turnuvayı binlerce farklı olasılıkla oynatır.": "The model does not declare one certain result; it plays the remaining tournament through thousands of possible outcomes.",
    "Tur Atlama Olasılık Matrisi": "Progression Probability Matrix",
    "Altın/Gümüş Grup, yarı final, final ve şampiyonluk ihtimalleri aynı anda izlenir.": "Gold/Silver Group, semi-final, final and championship probabilities are tracked together.",
    "Yarı Final": "Semi-final",
    "Tahmini Lig": "Projected League",
    "En Olası Turnuva Akışı": "Most Likely Tournament Path",
    "Modelin mevcut veriden ürettiği tek ana senaryo. Kesin sonuç değil, en yüksek olasılıklı yol haritasıdır.": "The primary scenario generated from current data. It is not a certain result, but the highest-probability roadmap.",
    "Simüle Eleme Ağacı": "Simulated Knockout Bracket",
    "Üç maçlık serilerde iki galibiyete ulaşan oyuncu tur atlar; final tek maçtır.": "The first player to two wins advances in best-of-three series; the final is a single match.",
    "Eleme Serileri": "Knockout Series",
    "TAHMİNİ FİNAL": "PROJECTED FINAL",
    "Kalan Tüm Maçların Model Tahmini": "Model Predictions for All Remaining Matches",
    "Simülasyon Motoru": "Simulation Engine",
    "Aynı gerçek veri bütün cihazlarda aynı model girdisini üretir.": "The same official data produces the same model input on every device.",
    "Son 20 maç formu": "Last-20 match form",
    "Tüm zamanlar gücü": "All-time strength",
    "Son 5 maç momentumu": "Last-five momentum",
    "FIFA 9 performansı": "FIFA 9 performance",
    "Gol / savunma profili": "Scoring / defensive profile",
    "İkili rekabet etkisi": "Head-to-head effect",
    "Dinamik çalışma:": "Dynamic operation:",
    "Skor Senaryosu Testi": "Score Scenario Test",
    "Resmî veriyi değiştirmeden kendi skor kombinasyonunu dene.": "Test your own score combination without changing official data.",
    "Turnuva Simülasyonu Kura Sonrası Açılır": "Tournament Simulation Opens After the Draw",
    "League Phase fikstürü oluşturulduğunda kalan bütün turnuva güncel performanslara göre binlerce kez otomatik oynatılır.": "Once the League Phase schedule is generated, the entire remaining tournament is automatically replayed thousands of times using current performance data.",
    "Turnuva simülasyonu güncel verilerle yeniden çalıştırıldı.": "The tournament simulation has been rerun with current data.",
    "Paylaşılacak simülasyon bulunmuyor.": "There is no simulation available to share.",
    "Gerçek sonuçlar sabitlenir; kalan turnuva güncel Elo, form ve performansa göre yeniden simüle edilir.": "Recorded results are locked in; the remaining tournament is resimulated using current Elo, form and performance.",
    "Baskı": "Pressure",
    "Kader Yolu": "Destiny Path",
    "Turnuva Güç Piyasası": "Tournament Power Market",
    "Baskı ve Mental Güç Merkezi": "Pressure & Mental Strength Centre",
    "Oyuncunun Kader Yolu": "Player Destiny Path",
    "Canlı Maç Nabzı": "Live Match Pulse",
    "Turnuvanın Dijital Sesi": "The Digital Voice of the Tournament",
    "Yeni Bülten Oluştur": "Generate New Briefing",
    "Direktör Sesi": "Director Voice",
    "GÜNLÜK DİREKTÖR BÜLTENİ": "DAILY DIRECTOR BRIEFING",
    "Bugünün Kontrol Paneli": "Today's Control Panel",
    "Direktör Protokolü": "Director Protocol",
    "Mental Güç Sıralaması": "Mental Strength Ranking",
    "Piyasa Lideri": "Market Leader",
    "En Güçlü Yükseliş": "Top Gainer",
    "En Sert Düşüş": "Top Decliner",
    "Gizli Değer": "Hidden Value",
    "En Volatil": "Most Volatile",
    "Sıradaki Kader Maçı": "Next Destiny Match",
    "En Olası Yolculuk": "Most Likely Journey",
    "Maç Kontrolü": "Match Control",
    "Baskı Seviyesi": "Pressure Level",
    "Kaos Endeksi": "Chaos Index",
    "Geri Dönüş İhtimali": "Comeback Probability",
    "Sonraki Gol Sinyali": "Next Goal Signal",
    "Canlı Olasılık Akışı": "Live Probability Flow",
    "Nabız Yorumu": "Pulse Commentary",
    "Rozetler, Ünvanlar & Prestige": "Badges, Titles & Prestige",
    "Kolay başlangıç başarılarından tarihî Mitik ünvanlara uzanan, zorluk derecesi ve nadirliğe göre sınıflandırılmış yaşayan kariyer sistemi.": "A living career system ranging from accessible starter achievements to historic Mythic titles, classified by difficulty and rarity.",
    "Prestige Level Kartları": "Prestige Level Cards",
    "Her seviye ayrı renk, ışık modeli ve kart kimliği kullanır.": "Every level uses a distinct colour, lighting model and card identity.",
    "Kariyer Prestige Sıralaması": "Career Prestige Ranking",
    "Elo güncel gücü, Prestige ise kariyer mirası ve başarı çeşitliliğini temsil eder.": "Elo represents current strength, while Prestige represents career legacy and achievement diversity.",
    "Oyuncu Rozet Vitrinleri": "Player Badge Cabinets",
    "En nadir başarımlar, aktif ünvan ve bir sonraki hedefler.": "The rarest achievements, active title and next targets.",
    "İlk rozet için mücadele devam ediyor.": "The chase for the first badge continues.",
    "SONRAKİ HEDEFLER": "NEXT TARGETS",
    "Bütün açık hedefler tamamlandı.": "All visible targets have been completed.",
    "Canlı İlerleme Merkezi": "Live Progress Centre",
    "Her oyuncunun tamamlanmış ve kilitli rozetleri gerçek zamanlı ilerleme ile izlenir.": "Every player's completed and locked badges are tracked with real-time progress.",
    "Gizli Mitik Başarım": "Secret Mythic Achievement",
    "Koşulu açılana kadar görünmez.": "The condition remains hidden until unlocked.",
    "Gizli Başarım": "Hidden Achievement",
    "Koşul keşfedilene kadar gizli kalır.": "The condition remains hidden until it is discovered.",
    "KİLİTLİ": "LOCKED",
    "TAMAMLANDI": "COMPLETED",
    "Zorluk": "Difficulty",
    "Temel ödül": "Base reward",
    "Başarımlar": "Achievements",
    "rozet": "badges",
    "ROZET": "BADGES",
    "tamamlandı": "completed",
    "En yüksek seri": "Peak runs",
    "Kalan Tüm Maçların Gelişmiş Model Tahmini": "Advanced Model Predictions for All Remaining Matches",
    "Tekrarlayan yuvarlak skorlar yerine her eşleşmeye özel tempo, xG-benzeri beklenen skor, volatilite ve kalibre edilmiş skor dağılımı.": "Instead of repetitive rounded scores, each matchup receives its own tempo, xG-like expected score, volatility and calibrated score distribution.",
    "Tahmini Maç": "Predicted Matches",
    "Farklı Skor": "Unique Scorelines",
    "Ortalama Gol": "Average Goals",
    "Yakın Maç": "Close Matches",
    "Sürpriz Yol": "Upset Paths",
    "Kalan maç bulunmuyor; turnuva tamamlandı.": "No remaining matches; the tournament is complete.",
    "Skoru yalnızca ortalamayı yuvarlayarak değil, bütün olası skorları olasılık matrisi içinde hesaplayarak üretir.": "Generates scores by evaluating the full score-probability matrix rather than simply rounding an average.",
    "Az veriyi lig ortalamasına yaklaştıran güvenilirlik düzeltmesi": "Reliability adjustment that shrinks limited data toward the league average",
    "Oyuncu hücumu × rakip savunma zayıflığı": "Player attack × opponent defensive vulnerability",
    "Poisson’dan daha gerçekçi aşırı dağılımlı gol modeli": "Overdispersed goal model that is more realistic than Poisson",
    "Skor matrisi dinamik oran olasılıklarına kalibre edilir": "The score matrix is calibrated to dynamic 1-X-2 probabilities",
    "Lig, eleme ve final aşamasına özel maç ritmi": "Stage-specific match rhythm for league, knockout and final rounds",
    "Sonuç değişmedikçe sabit, veri değişince tamamen yenilenen ana yol": "A stable main path until real data changes, then fully recalculated",
    "Neden daha gerçekçi?": "Why is it more realistic?",
    "xG-benzeri beklenen skor": "xG-like expected score",
    "Skor olasılığı": "Score probability",
    "Model güveni": "Model confidence",
    "Volatilite": "Volatility",
    "Alternatif skorlar": "Alternative scorelines",
    "Model Senaryosu": "Model Scenario",
    "Sürpriz Senaryo": "Upset Scenario",
    "Skor Patlaması": "Score Explosion",
    "Gol Düellosu": "Goal Duel",
    "Dominant Sonuç": "Dominant Result",
    "Denge Senaryosu": "Balanced Scenario",
    "İnce Marj": "Fine Margin",
    "Gol Fırtınası": "Goal Storm",
    "Açık Oyun": "Open Game",
    "Taktik Savaş": "Tactical Battle",
    "Dengeli Tempo": "Balanced Tempo",
    "Sıradaki iki turun maçları.": "Matches from the next two rounds.",
    "Yalnızca girilen senaryonun anlık sonucu.": "The live result of the entered scenario only.",
    "Yarı Finaller": "Semi-finals",
    "Temizle": "Clear",
    "Premium Oyuncu Kimlik Kartları": "Premium Player Identity Cards",
    "Prestige uyumlu model": "Prestige-driven design",
    "12 performans metriği": "12 performance metrics",
    "Canlı kariyer güncellemesi": "Live career updates",
    "Oyuncu performans radar grafiği": "Player performance radar chart",
    "Performans DNA’sı": "Performance DNA",
    "Kart değeri yalnızca sonuca değil; form, rakip kalitesi, baskı performansı, kariyer mirası ve oyun çeşitliliğine dayanır.": "The card rating is based not only on results, but also form, opponent quality, pressure performance, career legacy and playing versatility.",
    "ANA METRİKLER": "CORE METRICS",
    "İLERİ METRİKLER": "ADVANCED METRICS",
    "ŞAMPİYONLUK YOLU": "TITLE PATH",
    "AKTİF SERİ": "ACTIVE RUN",
    "KARİYER MAÇI": "CAREER MATCHES",
    "GALİBİYET": "WINS",
    "ŞAMPİYONLUK": "TITLES",
    "FAVORİ TAKIM": "FAVOURITE TEAM",
    "TAKIM ÇEŞİTLİLİĞİ": "TEAM VARIETY",
    "KARTIN EN GÜÇLÜ TARAFI": "CARD SIGNATURE",
    "GELİŞİM ALANI": "DEVELOPMENT AREA",
    "KART MODELİ": "CARD MODEL",
    "Elo ve Kariyer Hareketi": "Elo & Career Movement",
    "Premium Kart Koleksiyonu": "Premium Card Collection",
    "Beş turun 15 maçı, skor alanları ve kümülatif puan tablosu tek sayfada.": "All 15 matches across five rounds, score fields and cumulative standings on one page.",
    "Tek Sayfa · A4 Yatay": "Single Page · A4 Landscape",
  };

  const reverse = Object.fromEntries(Object.entries(dictionary).map(([tr, en]) => [en, tr]));

  function currentLanguage() {
    return supported.has(localStorage.getItem(STORAGE_KEY)) ? localStorage.getItem(STORAGE_KEY) : initial;
  }

  function translateExact(value, lang = currentLanguage()) {
    if (lang === "tr") return reverse[value] || value;
    return dictionary[value] || value;
  }

  function translateDynamic(value, lang = currentLanguage()) {
    if (lang !== "en") return value;
    let text = value;
    const patterns = [
      [/^(\d+) AÇILAN ROZET$/, "$1 BADGES UNLOCKED"],
      [/^([\d.,]+) TOPLAM XP$/, "$1 TOTAL XP"],
      [/^(\d+) KARİYER HEDEFİ$/, "$1 CAREER TARGETS"],
      [/^(.+) Başarımlar$/, "$1 Achievements"],
      [/^Zorluk (\d+)\/7 · Temel ödül ([\d.,]+) Prestige XP$/, "Difficulty $1/7 · Base reward $2 Prestige XP"],
      [/^(\d+) ROZET$/, "$1 BADGES"],
      [/^(\d+) rozet · ([\d.,]+) XP$/, "$1 badges · $2 XP"],
      [/^(\d+)\/(\d+) tamamlandı$/, "$1/$2 completed"],
      [/^En yüksek seri: (\d+)W · (\d+)U$/, "Peak runs: $1W · $2U"],
      [/^(.+) için (\d+) XP$/, "$2 XP to $1"],
      [/^(\d+) maç yenilmez$/, "$1 matches unbeaten"],
      [/^(\d+) aktif kart$/, "$1 active cards"],
      [/^Genel ilerleme %(\d+)$/, "Overall progress $1%"],
      [/^(\d+) \/ 16 oyuncu$/, "$1 / 16 players"],
      [/^Oyuncu (\d+)$/, "Player $1"],
      [/^(\d+)\. TUR$/, "ROUND $1"],
      [/^Maç (\d+)$/, "Match $1"],
      [/^(\d+) maç$/, "$1 matches"],
      [/^(\d+) gol$/, "$1 goals"],
      [/^(\d+) oyuncu$/, "$1 players"],
      [/^(\d+) farklı oyuncu$/, "$1 different players"],
      [/^(\d+)× Şampiyon$/, "$1× Champion"],
      [/^Şampiyonluk · (\d+) final · (\d+) podyum$/, "Titles · $1 finals · $2 podiums"],
      [/^(.+) · (\d+) puan$/, "$1 · $2 points"],
      [/^(.+) · (\d+) puan · ([+\-]?\d+) averaj$/, "$1 · $2 points · $3 goal difference"],
      [/^Penaltı galibi: (.+)$/, "Penalty winner: $1"],
      [/^Tur atlayan: (.+)$/, "Advanced: $1"],
      [/^(.+) · ŞAMPİYON$/, "$1 · CHAMPION"],
      [/^ŞAMPİYON: (.+)$/, "CHAMPION: $1"],
      [/^(\d+) oyuncu adı uygulandı\.$/, "$1 player names applied."],
      [/^(.+) Grup henüz oluşmadı$/, "$1 Group has not been generated yet"],
      [/^League Phase \+ (Altın|Gümüş) Grup sonuçları birlikte hesaplanır\.$/, (_, g) => `League Phase + ${g === "Altın" ? "Gold" : "Silver"} Group results are calculated together.`],
      [/^(Altın|Gümüş) Grup Fikstürü$/, (_, g) => `${g === "Altın" ? "Gold" : "Silver"} Group Schedule`],
      [/^(Altın|Gümüş) Grup$/, (_, g) => `${g === "Altın" ? "Gold" : "Silver"} Group`],
      [/^(\d+) Maç · (\d+) Gol$/, "$1 Matches · $2 Goals"],
      [/^(.+) karşısında final galibiyeti$/, "won the final against $1"],
      [/^(\d+) şampiyonluk · (\d+) final$/, "$1 titles · $2 finals"],
      [/^(\d+) final · (\d+) podyum$/, "$1 finals · $2 podiums"],
      [/^(\d+) galibiyet · (\d+) puan$/, "$1 wins · $2 points"],
      [/^(\d+) gol · maç başı ([\d.]+)$/, "$1 goals · $2 per match"],
      [/^Maç başı ([\d.]+) gol yedi$/, "Conceded $1 goals per match"],
      [/^(.+) karşısında (\d+)-(\d+) · (\d+) fark · FIFA (\d+)$/, "$2-$3 vs $1 · $4 margin · FIFA $5"],
      [/^(\d+) maç · (\d+)-(\d+)-(\d+) rekabet özeti$/, "$1 matches · rivalry snapshot $2-$3-$4"],
      [/^(\d+) maç$/, "$1 matches"],
      [/^(\d+) clean sheet$/, "$1 clean sheets"],
      [/^(\d+) edisyon$/, "$1 editions"],
      [/^(\d+) seçim · (\d+) oyuncu$/, "$1 selections · $2 players"],
      [/^(\d+) puan · (\d+) galibiyet$/, "$1 points · $2 wins"],
      [/^([\d.]+) PPG · minimum (\d+) seçim$/, "$1 PPG · minimum $2 selections"],
      [/^(\d+) gol · maç başı ([\d.]+)$/, "$1 goals · $2 per match"],
      [/^(\d+) TAKIM SEÇİMİ$/, "$1 TEAM SELECTIONS"],
      [/^(\d+) TAKIM$/, "$1 TEAMS"],
      [/^(\d+) oyuncu · (\d+) turnuva · (\d+) gol$/, "$1 players · $2 tournaments · $3 goals"],
      [/^(\d+) seçim · (\d+) farklı oyuncu · (\d+) turnuva$/, "$1 selections · $2 different players · $3 tournaments"],
      [/^(\d+) takım seçimi · (\d+) farklı takım$/, "$1 team selections · $2 different teams"],
      [/^(.+) · (\d+) maç$/, "$1 · $2 matches"],
      [/^(.+) · (\d+) galibiyet$/, "$1 · $2 wins"],
      [/^(.+) · (\d+) puan$/, "$1 · $2 points"],
      [/^(.+) · ([\d.]+) PPG$/, "$1 · $2 PPG"],
      [/^([+\-]?\d+) toplam averaj$/, "$1 total goal difference"],
      [/^Maç başı ([\d.]+) gol$/, "$1 goals per match"],
      [/^(\d+) farklı oyuncu$/, "$1 different players"],
      [/^(\d+) performans puanı · (\d+) galibiyet$/, "$1 performance points · $2 wins"],
      [/^Maç başı ([\d.]+)$/, "$1 per match"],
      [/^(\d+) galibiyet · (\d+) maç$/, "$1 wins · $2 matches"],
      [/^(\d+) gol · ([\d.]+) gol\/maç$/, "$1 goals · $2 goals/match"],
      [/^([\d.]+) yenilen gol\/maç$/, "$1 goals conceded/match"],
      [/^(\d+) form puanı · (.+)$/, "$1 form points · $2"],
      [/^(\d+) maç üst üste$/, "$1 matches in a row"],
      [/^(\d+) gol farkı$/, "$1-goal margin"],
      [/^(\d+) toplam gol$/, "$1 total goals"],
      [/^(\d+) seçim · (\d+) puan · ([\d.]+) PPG$/, "$1 selections · $2 points · $3 PPG"],
      [/^(\d+) maç · ([\d.]+)% galibiyet$/, "$1 matches · $2% wins"],
      [/^(\d+)G seri$/, "$1W streak"],
      [/^(\d+)M seri$/, "$1L streak"],
      [/^(\d+)B seri$/, "$1D streak"],
      [/^League Phase #(\d+)$/, "League Phase #$1"],
      [/^Altın Grup #(\d+)$/, "Gold Group #$1"],
      [/^Gümüş Grup #(\d+)$/, "Silver Group #$1"],
      [/^(\d+) oynanmamış fikstür canlı yayına hazır\.$/, "$1 unplayed fixtures are ready to go live."],
      [/^(\d+) OLAY$/, "$1 EVENTS"],
      [/^(\d+) MAÇ$/, "$1 MATCHES"],
      [/^Son güncelleme (.+)$/, "Last update $1"],
      [/^Son (5|10|20) Maç Form Merkezi$/, "Last $1 Match Form Centre"],
      [/^Son (5|10|20) Lideri$/, "Last $1 Leader"],
      [/^Son (5|10|20) maç performansı\. Kart seçerek detay panelini aç\.$/, "Last $1 match performance. Select a card to open the detail panel."],
      [/^Son (5|10|20) Maç Puan Durumu$/, "Last $1 Match Standings"],
      [/^Oyuncuların en güncel (5|10|20) maçına göre hesaplanan bağımsız form puan durumu, performans endeksi, seri analizi ve maç maç form çizgisi\. FIFA 9 sonuçları girildikçe otomatik yenilenir\.$/, "Independent form standings, performance index, streak analysis and match-by-match form line calculated from each player’s latest $1 matches. It updates automatically as FIFA 9 results are entered."],
      [/^(\d+)\/(5|10|20) maç kapsama$/, "$1/$2 match coverage"],
      [/^(\d+) puan · ([\d.]+) PPG · (\d+)\/100 form$/, "$1 points · $2 PPG · $3/100 form"],
      [/^(\d+)\/15 puan · (.+)$/, "$1/15 points · $2"],
      [/^(\d+) maç · (.+)$/, "$1 matches · $2"],
      [/^([+\-]?\d+) puan trendi · (.+)$/, "$1-point trend · $2"],
      [/^(\d+) galibiyet$/, "$1 wins"],
      [/^(\d+) beraberlik$/, "$1 draws"],
      [/^(\d+) mağlubiyet$/, "$1 losses"],
      [/^(\d+) maç üst üste$/, "$1 matches in a row"],
      [/^(\d+) puan · (\d+) maç$/, "$1 points · $2 matches"],
      [/^(\d+) gol · ([\d.]+) gol\/maç$/, "$1 goals · $2 goals/match"],
      [/^([+\-]?\d+) averaj · (\d+)-(\d+)$/, "$1 goal difference · $2-$3"],
      [/^([\d.]+) gol\/maç · (\d+) clean sheet$/, "$1 goals/match · $2 clean sheets"],
      [/^([\d.]+)% · (\d+)\/(\d+)$/, "$1% · $2/$3"],
      [/^(\d+) kullanım$/, "$1 uses"],
      [/^(\d+) oynanmamış fikstür · oranlar resmî sonuç girildiğinde otomatik değişir\.$/, "$1 unplayed fixtures · odds change automatically when an official result is entered."],
      [/^(\d+) oynanmamış fikstür$/, "$1 unplayed fixtures"],
      [/^(\d+) güç · (\d+)\/20 veri$/, "$1 strength · $2/20 data"],
      [/^(\d+) form maçı · ([\d.]+) PPG · (\d+)-(\d+) gol$/, "$1 form matches · $2 PPG · $3-$4 goals"],
      [/^(\d+)-(\d+)-(\d+) · (\d+) maç$/, "$1-$2-$3 · $4 matches"],
      [/^X olasılığı (\d+)% · ([\d.]+) oran$/, "Draw probability $1% · odds $2"],
      [/^(.+) · (\d+)% kazanma ihtimali$/, "$1 · $2% win probability"],
      [/^(.+) · (\d+)% · ([\d.]+) oran$/, "$1 · $2% · odds $3"],
      [/^Genel H2H: (.+)$/, "Overall H2H: $1"],
      [/^(\d+) form maçı$/, "$1 form matches"],
      [/^Son güncelleme: (.+)$/, "Last update: $1"]
    ];
    for (const [pattern, replacement] of patterns) {
      if (pattern.test(text)) {
        text = text.replace(pattern, replacement);
        break;
      }
    }
    return text;
  }

  function translateString(value, lang = currentLanguage()) {
    if (value == null) return value;
    const raw = String(value);
    const leading = raw.match(/^\s*/)?.[0] || "";
    const trailing = raw.match(/\s*$/)?.[0] || "";
    const core = raw.trim();
    if (!core) return raw;
    const exact = translateExact(core, lang);
    const dynamic = exact === core ? translateDynamic(core, lang) : exact;
    return leading + dynamic + trailing;
  }

  function shouldSkip(node) {
    const parent = node.parentElement;
    if (!parent) return false;
    return Boolean(parent.closest("script, style, noscript, [data-no-translate]"));
  }

  function translateNode(root = document.body) {
    const lang = currentLanguage();
    document.documentElement.lang = lang;
    document.documentElement.dataset.language = lang;
    document.title = lang === "en" ? "FIFA 9 Tournament Hub" : "FIFA Turnuva Merkezi";
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.content = lang === "en"
      ? "FIFA Tournament Hub — FIFA 9 League Phase, live standings, fixtures, knockout series and an eight-tournament archive."
      : "FIFA Turnuva Merkezi — FIFA 9 League Phase, canlı puan tabloları, fikstür, eleme serileri ve 8 turnuvalık arşiv.";

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    while (walker.nextNode()) textNodes.push(walker.currentNode);
    for (const node of textNodes) {
      if (shouldSkip(node)) continue;
      const translated = translateString(node.nodeValue, lang);
      if (translated !== node.nodeValue) node.nodeValue = translated;
    }

    if (lang === "en") {
      const headerMap = { "O": "MP", "G": "W", "B": "D", "M": "L", "AG": "GF", "YG": "GA", "AV": "GD", "P": "Pts" };
      const headers = root.querySelectorAll?.("th") || [];
      for (const header of headers) {
        const key = header.textContent.trim();
        if (headerMap[key]) header.textContent = headerMap[key];
      }
    }

    const elements = root.querySelectorAll?.("[placeholder], [title], [aria-label]") || [];
    for (const element of elements) {
      for (const attr of ["placeholder", "title", "aria-label"]) {
        if (!element.hasAttribute(attr)) continue;
        const current = element.getAttribute(attr);
        const translated = translateString(current, lang);
        if (translated !== current) element.setAttribute(attr, translated);
      }
    }
    updateSwitcher();
  }

  let translating = false;
  function guardedTranslate(root) {
    if (translating) return;
    translating = true;
    try { translateNode(root); } finally { translating = false; }
  }

  function setLanguage(lang) {
    if (!supported.has(lang)) return;
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang;
    location.reload();
  }

  function updateSwitcher() {
    const lang = currentLanguage();
    document.querySelectorAll("[data-language-option]").forEach(button => {
      const active = button.dataset.languageOption === lang;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", String(active));
    });
  }

  document.addEventListener("click", event => {
    const button = event.target.closest("[data-language-option]");
    if (button) setLanguage(button.dataset.languageOption);
  });

  const observer = new MutationObserver(mutations => {
    if (translating) return;
    const roots = new Set();
    for (const mutation of mutations) {
      if (mutation.type === "characterData") roots.add(mutation.target.parentElement || document.body);
      mutation.addedNodes?.forEach(node => {
        if (node.nodeType === Node.ELEMENT_NODE) roots.add(node);
        else if (node.parentElement) roots.add(node.parentElement);
      });
    }
    roots.forEach(root => guardedTranslate(root));
  });

  window.FIFA_I18N = {
    get language() { return currentLanguage(); },
    setLanguage,
    t: translateString,
    translate: guardedTranslate
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => {
      guardedTranslate(document.body);
      observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    });
  } else {
    guardedTranslate(document.body);
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  }
})();
