(() => {
  "use strict";
  const VERSION = "44.2.1";
  const STORAGE_KEY = "fifa-language-v44";
  const originalText = new WeakMap();
  const originalAttributes = new WeakMap();
  let busy = false;
  let observer = null;

  const exact = new Map(Object.entries({

    "KAYIT KURTARMA MERKEZİ": "SAVE RECOVERY CENTRE",
    "KAYITLARI TARA VE KURTAR": "SCAN AND RECOVER SAVES",
    "JSON YEDEĞİ YÜKLE": "IMPORT JSON BACKUP",
    "MANAGER YEDEĞİ AL": "EXPORT MANAGER BACKUP",
    "TURNUVA MERKEZİNE DÖN": "RETURN TO TOURNAMENT HUB",
    "Kariyer kaydedildi. Ana oyun ekranına dönüldü.": "Career saved. Returned to the game title screen.",
    "Kurtarılabilir ek Manager kaydı bulunamadı.": "No additional recoverable Manager save was found.",
    "Manager yedeği indirildi.": "Manager backup exported.",
    "Hiçbir kariyeri silmez.": "It does not delete any career.",
    "Ana menü": "Main menu",
    "Menüyü aç": "Open menu",
    "Duyuruyu kapat": "Close announcement",
    "Siteye Devam Et": "Continue to Site",
    "FIFA TURNUVA MERKEZİ": "FIFA TOURNAMENT HUB",
    "Turnuva Organizasyonu Hakkında Duyuru": "Tournament Organisation Announcement",
    "Anlayışınız için teşekkür ederim.": "Thank you for your understanding.",
    "Dashboard": "Dashboard",
    "Canlı Maç": "Live Match",
    "Canlı Maç Merkezi": "Live Match Centre",
    "Canlı İstatistikler": "Live Statistics",
    "Form Merkezi": "Form Centre",
    "Maç Oranları": "Match Odds",
    "Turnuva Zekâ Merkezi": "Tournament Intelligence Centre",
    "Zekâ Merkezi": "Intelligence Centre",
    "Turnuva Sohbeti": "Tournament Chat",
    "Sohbet": "Chat",
    "Kura & Oyuncular": "Draw & Players",
    "Altın Grup": "Gold Group",
    "Gümüş Grup": "Silver Group",
    "Eleme Aşaması": "Knockout Stage",
    "Çıktı Merkezi": "Print Centre",
    "Turnuva Arşivi": "Tournament Archive",
    "Sezonlar & Kupa Müzesi": "Seasons & Trophy Museum",
    "FIFA Lig Sistemi": "FIFA League System",
    "Tüm Zamanlar": "All-Time Records",
    "Takım İstatistikleri": "Team Statistics",
    "Veri & Yedek": "Data & Backup",
    "Canlı bağlantı hazırlanıyor": "Preparing live connection",
    "Canlı bağlantı": "Live connection",
    "Bağlanıyor": "Connecting",
    "Bağlanıyor…": "Connecting…",
    "Yerel mod": "Local mode",
    "Bulut kurulumu bekleniyor": "Cloud setup pending",
    "Veri yükleniyor": "Loading data",
    "Kaydediliyor": "Saving",
    "Canlı · kaydedildi": "Live · saved",
    "Canlı · yönetici": "Live · administrator",
    "Canlı · izleyici": "Live · viewer",
    "Canlı · oyuncu": "Live · player",
    "Yeniden bağlanıyor": "Reconnecting",
    "Bağlantı hatası": "Connection error",
    "Yedek Al": "Create Backup",
    "Yönetici Girişi": "Administrator Login",
    "Oyuncu / Yönetici Girişi": "Player / Administrator Login",
    "Bulut Kurulumu": "Cloud Setup",
    "Yönetici · Çıkış": "Administrator · Sign Out",
    "Kapat": "Close",
    "Vazgeç": "Cancel",
    "Kaydet": "Save",
    "Devam Et": "Continue",
    "Duraklat": "Pause",
    "Taktik": "Tactics",
    "Maç Merkezinden Çık": "Exit Match Centre",
    "Olay Akışını Aç": "Show Event Stream",
    "Olay Akışını Kapat": "Hide Event Stream",
    "Gelişmiş Maç Analizi": "Advanced Match Analysis",
    "Canlı Maç Anlatımı": "Live Match Commentary",
    "Oyun Hızı": "Game Speed",
    "Maç Planı": "Match Plan",
    "Maç Planı Otopsisi": "Match Plan Autopsy",
    "Top Bizdeyken": "In Possession",
    "Top Rakipteyken": "Out of Possession",
    "Topu Kazanınca": "After Winning Possession",
    "Topu Kaybedince": "After Losing Possession",
    "Koşullu Taktik Emirleri": "Conditional Tactical Orders",
    "Rol Uyumu": "Role Compatibility",
    "Geçiş Güvenliği": "Transition Security",
    "Genişlik": "Width",
    "Merkez Kontrolü": "Central Control",
    "Fizik Yükü": "Physical Load",
    "Topa Sahip Olma": "Possession",
    "Şut": "Shots",
    "İsabetli Şut": "Shots on Target",
    "Büyük Fırsat": "Big Chances",
    "Pas": "Passes",
    "Pas İsabeti": "Pass Accuracy",
    "Korner": "Corners",
    "Faul": "Fouls",
    "Sarı Kart": "Yellow Cards",
    "Kırmızı Kart": "Red Cards",
    "Gol": "Goal",
    "Penaltı": "Penalty",
    "Penaltı Kaçtı": "Penalty Missed",
    "Büyük Şans": "Big Chance",
    "Mutlak Gol Kaçtı": "Huge Chance Missed",
    "Tehlikeli Baskı": "Dangerous Pressure",
    "Atak": "Attack",
    "Not": "Note",
    "Nötr": "Neutral",
    "Maç Sonucu": "Match Result",
    "Maç sonucu kaydedildi.": "Match result saved.",
    "Maç sonucu temizlendi.": "Match result cleared.",
    "Takım": "Team",
    "Oyuncu": "Player",
    "Oyuncular": "Players",
    "Maç": "Match",
    "Maçlar": "Matches",
    "Galibiyet": "Win",
    "Galibiyetler": "Wins",
    "Beraberlik": "Draw",
    "Mağlubiyet": "Loss",
    "Puan": "Points",
    "Averaj": "Goal Difference",
    "Gol Attı": "Goals For",
    "Gol Yedi": "Goals Against",
    "Sıra": "Rank",
    "Durum": "Status",
    "Fikstür": "Fixtures",
    "Sonuçlar": "Results",
    "Puan Durumu": "Standings",
    "Liglerin tamamlanması bekleniyor": "Waiting for the leagues to be completed",
    "Kupayı Başlat": "Start the Cup",
    "ŞAMPİYON": "CHAMPION",
    "Doğrudan Yarı Final": "Direct Semi-final Qualification",
    "Yarı Final": "Semi-final",
    "Yarı Final 1": "Semi-final 1",
    "Yarı Final 2": "Semi-final 2",
    "BÜYÜK FİNAL · TEK MAÇ · AYNI TAKIM": "GRAND FINAL · SINGLE MATCH · SAME TEAM",
    "Ortak takım henüz belirlenmedi": "Shared team has not been selected yet",
    "Final Sonucunu Düzenle": "Edit Final Result",
    "Final Sonucu Gir": "Enter Final Result",
    "Oruç Reis Kupası tamamlandı": "Oruç Reis Cup completed",
    "Süper Kupayı Oluştur": "Create the Super Cup",
    "Yeni sezon öncesi şampiyonlar maçı": "Champions match before the new season",
    "Oruç Reis Kupasının tamamlanması bekleniyor": "Waiting for the Oruç Reis Cup to be completed",
    "Sezonun büyük eleme kupası": "The season's major knockout cup",
    "Resmî sezon aktif": "Official season active",
    "Test sezonu aktif": "Test season active",
    "Fikstür hazır": "Fixtures ready",
    "Oyuncu kayıtları hazırlanıyor": "Preparing player registrations",
    "İptal edildi": "Cancelled",
    "Sezon tamamlandı": "Season completed",
    "ÖDÜLLER HAZIR": "AWARDS READY",
    "KESİNLEŞTİ": "FINALIZED",
    "DEVRE DEVAM EDİYOR": "LEG IN PROGRESS",
    "Devrenin Oyuncusu": "Player of the Leg",
    "Gol Kralı": "Top Scorer",
    "Defans Ödülü": "Defensive Award",
    "Henüz belirlenmedi": "Not yet determined",
    "Devrenin tamamlanması bekleniyor": "Waiting for the leg to be completed",
    "Ödülleri Yeniden Hesapla": "Recalculate Awards",
    "Ödülleri Kesinleştir": "Finalize Awards",
    "Şimdi müsait": "Available now",
    "Bu akşam müsait": "Available this evening",
    "Bugün uygun değil": "Unavailable today",
    "Maç teklifine açık": "Open to match offers",
    "Takım Havuzu": "Team Pool",
    "Takımlar": "Teams",
    "Havuzu Kaydet": "Save Pool",
    "Takım havuzları kilitlendi.": "Team pools locked.",
    "Takım havuzlarının kilidi açıldı.": "Team pools unlocked.",
    "Yedekleme İşlemleri": "Backup Operations",
    "FIFA 9 JSON Yedeği": "FIFA 9 JSON Backup",
    "Yedeği İndir": "Download Backup",
    "Yedeği Geri Yükle": "Restore Backup",
    "JSON Dosyası Seç": "Select JSON File",
    "Maçları CSV Olarak Al": "Export Matches as CSV",
    "CSV İndir": "Download CSV",
    "Oyuncu Listesi": "Player List",
    "Oyuncuları İndir": "Download Players",
    "FIFA 9 Verisini Sıfırla": "Reset FIFA 9 Data",
    "Güncel Turnuvayı Sıfırla": "Reset Current Tournament",
    "Kaynak Arşiv": "Source Archive",
    "Simülasyonu Yenile": "Refresh Simulation",
    "WhatsApp’ta Paylaş": "Share on WhatsApp",
    "WhatsApp'ta Paylaş": "Share on WhatsApp",
    "Dinamik Turnuva Simülasyonu": "Dynamic Tournament Simulation",
    "Turnuva simülasyonu güncel verilerle yeniden çalıştırıldı.": "Tournament simulation rerun with current data.",
    "Sıralamayı Yeniden Hesapla": "Recalculate Standings",
    "Temizle": "Clear",
    "Skor Senaryoları": "Score Scenarios",
    "Simüle Puan Durumu": "Simulated Standings",
    "Sıradaki iki turun maçları.": "Matches from the next two rounds.",
    "Yalnızca girilen senaryonun anlık sonucu.": "Live outcome of the entered scenario only.",
    "Kura Sayfasına Git": "Go to Draw Page",
    "Simülasyon verisi oluşturulamadı.": "Simulation data could not be generated.",
    "Canlı Olasılık ve Maç Kontrolü": "Live Probability & Match Control",
    "Maç Hikâyesi ve AI Yorum": "Match Story & AI Commentary",
    "Momentum Özeti": "Momentum Summary",
    "Ev Sahibi Son 15 dk": "Home Last 15m",
    "Deplasman Son 15 dk": "Away Last 15m",
    "Canlı Baskı": "Live Pressure",
    "Oyun Akışı": "Flow State",
    "Kritiklik": "Importance",
    "Liderlik Değişimi": "Lead Changes",
    "Canlı Dakika": "Live Minute",
    "Kazanma ihtimali": "Win probability",
    "Kazanırsa tahmini sıçrama": "Estimated upside with a win",
    "Kaybederse tahmini risk": "Estimated downside with a loss",
    "Sıradaki Kader Maçı": "Next Destiny Match",
    "En Olası Yolculuk": "Most Likely Journey",
    "İkinci Aşama": "Second Stage",
    "Olası Rakipler": "Likely Opponents",
    "Model Kararı": "Model Verdict",
    "Katılmadı": "No appearance",
    "OYUN TARZI": "PLAY STYLE",
    "FAVORİ TAKIM": "FAVOURITE TEAM",
    "Kariyer Güçlü Yönleri": "Career Strengths",
    "Kariyer Gelişim Alanları": "Career Development Areas",
    "Hızlı Gerçekler": "Quick Facts",
    "En Skor Yaptığı Maç": "Highest-Scoring Match",
    "En Zor Rakibe Karşı Galibiyet": "Hardest Opponent Win",
    "Galibiyet Serisi": "Win Streak",
    "Yenilmezlik": "Unbeaten Run",
    "PRESTİJ": "PRESTIGE",
    "KUPA": "TITLES",
    "GALİBİYET": "WINS",
    "MAÇ": "MATCHES",
    "PERFORMANSI": "PERFORMANCE",
    "Turnuva Performans Atlası": "Tournament Performance Atlas",
    "Henüz canlı olay girilmedi.": "No live event has been entered yet.",
    "Önce canlı maç başlatılmalı.": "A live match must be started first.",
    "Standart Görünüme Dön": "Exit Presentation",
    "TV / Projektör": "TV / Projector",
    "Yayın Görünümü": "Broadcast View",
    "İzleyici ekranını büyüt": "Enlarge the viewer experience",
    "Değişiklikler bu cihazda kaydedildi.": "Changes saved on this device.",
    "Değişiklikler canlı siteye kaydedildi.": "Changes saved to the live site.",
    "Bulut kaydı başarısız. İnternet bağlantısını ve yetkini kontrol et.": "Cloud save failed. Check your internet connection and permissions.",
    "Direktör bülteni güncel verilerle yenilendi.": "Director briefing refreshed with current data.",
    "Senaryo sıralaması yeniden hesaplandı.": "Scenario standings recalculated.",
    "Paylaşılacak simülasyon bulunmuyor.": "No simulation is available to share.",
    "Form Verisi Hazır Değil": "Form Data Is Not Ready",
    "Oyuncuları Aç": "Open Players",
    "Son 20 Maç Form Merkezi": "Last 20 Matches Form Centre",
    "Kura Bekleniyor": "Waiting for Draw",
    "League Phase Devam Ediyor": "League Phase in Progress",
    "Altın/Gümüş Aşaması Hazır": "Gold/Silver Stage Ready",
    "Resmî Kariyer": "Official Career",
    "Test Kariyeri": "Test Career",
    "Gerçek Oyun Modu": "Real Game Mode",
    "Test Modu": "Test Mode",
    "Oyundan Çık": "Exit Game"
  }));

  const paragraphTranslations = new Map(Object.entries({
    "Bu organizasyon; herkesin yoğun çalışma temposu içinde keyifli vakit geçirebileceği, dostça rekabet edebileceği ve birlikte güzel anılar biriktirebileceği bir ortam oluşturmak amacıyla planlandı. Aynı anlayışla, turnuvayı keyifle takip edebileceğiniz ve sizlere yakışan kapsamlı bir platform hazırlamak için büyük bir emek ve zaman harcandı.": "This event was created to give everyone a chance to relax, enjoy friendly competition and build good memories together despite a demanding work schedule. The same care and effort went into building a comprehensive platform worthy of the community following the tournament.",
    "Ancak süreç içerisinde organizasyonun başlangıçtaki eğlence ve birliktelik amacından uzaklaşmaya başladığını; bazı arkadaşlarımızın kendisini rahatsız, huzursuz veya keyifsiz hissettiğini gözlemledim. Bir etkinliğin insanları bir araya getirmesi gerekirken aramızdaki güzel arkadaşlık ortamını olumsuz etkileme ihtimali benim için turnuvanın devamından daha önemlidir.": "During the process, however, I observed that the event was moving away from its original purpose of enjoyment and togetherness, and that some colleagues felt uncomfortable or unhappy. Protecting the positive relationships between us matters more to me than continuing an event that should bring people together.",
    "Bu nedenle, herhangi bir arkadaşımızı hedef göstermeden veya kimseyi kırmadan, turnuva organizasyonunu bu noktada sonlandırma ve bundan sonraki FIFA turnuvalarının organizasyon sorumluluğunu üstlenmeme kararı aldım.": "For that reason, without singling anyone out or causing offence, I decided to end the tournament organisation at this point and not take responsibility for organising future FIFA tournaments.",
    "Bu karar herhangi bir kişiye karşı alınmış değildir. Tek amacım, gemide birlikte geçirdiğimiz zamanı, karşılıklı saygımızı ve arkadaşlık bağlarımızı korumaktır. Bugüne kadar turnuvaya katılan, destek veren, maçları takip eden ve organizasyona renk katan herkese içtenlikle teşekkür ederim.": "This decision is not directed at any individual. My only aim is to protect the time we share onboard, our mutual respect and our friendships. I sincerely thank everyone who participated, supported the event, followed the matches and contributed to the atmosphere.",
    "Umarım geriye rekabetten çok birlikte güldüğümüz ve keyif aldığımız güzel anlar kalır.": "I hope what remains are the good memories of laughing and enjoying the experience together, rather than the competition itself."
  }));

  const patterns = [
    [/^(\d+)\/(\d+) maç tamamlandı$/i, "$1/$2 matches completed"],
    [/^(\d+) gerçek sonuç sabitlendi$/i, "$1 real results locked"],
    [/^(\d+) maç$/i, "$1 matches"],
    [/^(\d+) gol$/i, "$1 goals"],
    [/^(\d+) puan$/i, "$1 points"],
    [/^(\d+) galibiyet$/i, "$1 wins"],
    [/^(\d+) gol yedi$/i, "$1 goals conceded"],
    [/^(\d+) gol yemeden maç$/i, "$1 clean sheets"],
    [/^(\d+)\. Devre$/i, "Leg $1"],
    [/^(\d+)\. devre$/i, "Leg $1"],
    [/^Son kayıt:\s*(.+)$/i, "Last saved: $1"],
    [/^Seri galibi:\s*(.+)$/i, "Series winner: $1"],
    [/^Ortak takım:\s*(.+)$/i, "Shared team: $1"],
    [/^Performans lideri:\s*(.+)$/i, "Performance leader: $1"],
    [/^Gol lideri:\s*(.+)$/i, "Goal leader: $1"],
    [/^En çok seçilen takım:\s*(.+)$/i, "Most selected team: $1"],
    [/^En farklı skor:\s*(.+)$/i, "Biggest winning margin: $1"],
    [/^Son güncelleme:\s*(.+)$/i, "Last update: $1"],
    [/^(.+) güncellendi\.$/i, "$1 updated."],
    [/^(.+) tamamlandı\.$/i, "$1 completed."],
    [/^(.+) kesinleşti\.$/i, "$1 finalized."],
    [/^(.+) oluşturuldu\.$/i, "$1 created."],
    [/^(.+) kaydedildi\.$/i, "$1 saved."],
    [/^(.+) için takım seçimi zorunludur\.$/i, "A team selection is required for $1."],
    [/^(.+), (.+) listesinde bulunmuyor\.$/i, "$1 is not included in the $2 list."],
    [/^(.+) bu takımı (\d+)\. devrede daha önce kullandı\.$/i, "$1 already used this team in Leg $2."],
    [/^FIFA (\d+) test taslağı oluşturuldu\. FIFA (\d+) verileri etkilenmedi\.$/i, "FIFA $1 test draft created. FIFA $2 data was not affected."],
    [/^FIFA (\d+) taslağı iptal edildi\. FIFA (\d+) aynen korunuyor\.$/i, "FIFA $1 draft cancelled. FIFA $2 remains unchanged."],
    [/^(.+) (\d+)\. devre bireysel ödülleri kesinleşti\.$/i, "$1 Leg $2 individual awards finalized."],
    [/^(.+) skorda üstünlüğü değiştirdi$/i, "$1 changed the lead"],
    [/^(.+) ile (.+) arasındaki karşılaşma (.+) tamamlandı\.$/i, "The match between $1 and $2 finished $3."],
    [/^(.+), (\d+) farklı geriden gelerek (.+) karşısında (.+) kazandı\.$/i, "$1 came back from $2 goals down to beat $3 $4."],
    [/^(.+), (.+) karşısında (\d+) farklı dominant bir galibiyet aldı\.$/i, "$1 recorded a dominant $3-goal win over $2."],
    [/^(.+), gol düellosuna dönüşen karşılaşmayı (.+) kazandı\.$/i, "$1 won a high-scoring shootout $2."],
    [/^(.+), dengeli mücadelede (.+) karşısında (.+) kazandı\.$/i, "$1 beat $2 $3 in a balanced contest."],
    [/^(.+) ve (.+), (.+) beraberlikle puanları paylaştı\.$/i, "$1 and $2 shared the points in a $3 draw."],
    [/^(.+) Elo sıralamasında (\d+) puanlık değişim yarattı\.$/i, "$1 produced a $2-point change in the Elo ranking."]
  ];

  const extraExact = {
  "Gerçek Oyun Modu": "Real Game Mode",
  "GERÇEK OYUN MODU": "REAL GAME MODE",
  "Gerçek Oyun Modunu Aç": "Start Real Game Mode",
  "GERÇEK OYUN MODUNU AÇ": "START REAL GAME MODE",
  "Resmî Kariyer": "Official Career",
  "RESMÎ KARİYER": "OFFICIAL CAREER",
  "Yeni Resmî Kariyer": "New Official Career",
  "YENİ RESMÎ KARİYER": "NEW OFFICIAL CAREER",
  "Test Laboratuvarı": "Test Laboratory",
  "TEST LABORATUVARINI AÇ": "OPEN TEST LABORATORY",
  "GELİŞTİRİCİ ALANI": "DEVELOPER AREA",
  "Yeni Test Kariyeri": "New Test Career",
  "YENİ TEST KARİYERİ": "NEW TEST CAREER",
  "Kayıtlı Kariyerler": "Saved Careers",
  "KAYITLI KARİYERLER": "SAVED CAREERS",
  "Kaldığın Yerden Devam Et": "Continue Where You Left Off",
  "Kariyere Devam Et": "Continue Career",
  "KARİYERE DEVAM ET": "CONTINUE CAREER",
  "Bulut Kariyerimi Aç": "Open My Cloud Career",
  "BULUT KARİYERİMİ AÇ": "OPEN MY CLOUD CAREER",
  "Henüz kayıtlı kariyer yok": "No saved careers yet",
  "Henüz resmî kariyer oluşturulmadı.": "No official career has been created yet.",
  "Henüz test kariyeri oluşturulmadı.": "No test career has been created yet.",
  "Kariyerden Çık": "Exit Career",
  "Kariyer kaydedildi ve gerçek oyun ana ekranına dönüldü.": "Career saved and returned to the real-game title screen.",
  "Gerçek Oyun Modu açıldı.": "Real Game Mode opened.",
  "Test Laboratuvarı açıldı.": "Test Laboratory opened.",
  "Son kayıt": "Last save",
  "MAÇ": "MATCH",
  "Yeni Kariyer": "New Career",
  "Kariyerimi Aç": "Open My Career",
  "Yeni Manager Kariyeri": "New Manager Career",
  "Manager Kariyerini Aç": "Open Manager Career",
  "Kariyeri Aç": "Open Career",
  "Kulübü Kur ve Evreni Oluştur": "Create Club and Build Universe",
  "Oyuncu kimliğin": "Your player identity",
  "Oyuncu seç": "Select player",
  "Kulüp adı": "Club name",
  "Kısa ad": "Short name",
  "6 haneli Manager PIN": "6-digit Manager PIN",
  "Ana renk": "Primary colour",
  "İkinci renk": "Secondary colour",
  "Test Kariyeri": "Test Career",
  "Takım kurasını tekrar deneyebilirsin.": "You may repeat the team draw.",
  "Kura kilitlenir ve Manager Hall'a bağlanır.": "The draw is locked and linked to Manager Hall.",
  "Başka cihazdaki kariyerine dön": "Return to your career on another device",
  "Gerçek oyuncu evrenine ilave kulüp olarak katılacaksın. Maç öncesi Avrupa kulüpleri, devrenin yıldız havuzundan kilitli kura ile belirlenecek.": "You will join the real-player universe as an additional club. Before each match, European clubs are selected through a locked draw from the leg's star pool.",
  "Resmî kariyer ile test çalışmalarını birbirinden ayır. Kariyerini güvenli biçimde kaydet, ana ekrana çık ve daha sonra kaldığın yerden devam et.": "Keep official career progress separate from testing. Save safely, return to the title screen and continue later from where you stopped.",
  "Tek çekim takım kurası, kalıcı sonuçlar, Manager ELO, sezon ilerlemesi ve mümkün olduğunda Supabase bulut kaydı.": "Single-draw team selection, persistent results, Manager ELO, season progression and Supabase cloud saves when available.",
  "Maç motoru, taktik seçenekleri ve takım kurasını resmî kariyer kayıtlarına karıştırmadan dene.": "Test the match engine, tactical options and team draws without mixing them into official career records.",
  "Yeniden kura kilitlidir": "Redraw is locked",
  "Resmî sonuç ve kariyer kaydı": "Official results and career records",
  "Manager PIN koruması": "Manager PIN protection",
  "Takım kurası tekrar edilebilir": "Team draws may be repeated",
  "Calibration ve Lab araçları açıktır": "Calibration and Lab tools are available",
  "Yerel kayıt yapısı kullanılır": "Local save structure is used",
  "Kariyerden Çık işlemi veriyi silmez; aktif kariyeri kapatıp bu ekrana döndürür.": "Exit Career does not delete data; it closes the active career and returns to this screen.",
  "Başka cihazdaki resmî kariyer": "Official career on another device",
  "Oyuncu adı ve altı haneli Manager PIN ile Supabase kaydını aç.": "Open the Supabase save using the player name and six-digit Manager PIN.",
  "Bugün": "Today",
  "Lig Evreni": "League Universe",
  "Oruç Reis Kupası": "Oruç Reis Cup",
  "İstatistik Merkezi": "Statistics Centre",
  "Canlı Maç": "Live Match",
  "AI Rakipler": "AI Opponents",
  "Fikstürlere Dön": "Back to Fixtures",
  "Kupa Kabini": "Trophy Cabinet",
  "Kullanıcı Seviyesi": "User Level",
  "Rekabetler & Derbiler": "Rivalries & Derbies",
  "Hall of Fame & Rekor Kitabı": "Hall of Fame & Record Book",
  "Takım Kurasına Geç": "Go to Team Draw",
  "Taktik Odasına Geç": "Go to Tactical Room",
  "Maç Raporunu Aç": "Open Match Report",
  "Canlı Maça Dön": "Return to Live Match",
  "Takım Kurasını Başlat": "Start Team Draw",
  "Test Kurasını Yenile": "Redraw Test Teams",
  "KURA DURUMU": "DRAW STATUS",
  "KİLİTLİ": "LOCKED",
  "AÇIK": "OPEN",
  "BEKLİYOR": "PENDING",
  "Takım kurası bekleniyor": "Waiting for team draw",
  "resmî olarak kilitli": "officially locked",
  "test modunda açık": "open in test mode",
  "Bu maç için yeniden çekilemez": "Cannot be redrawn for this match",
  "Test modunda tekrar çekilebilir": "May be redrawn in test mode",
  "İlk çekim kalıcıdır": "The first draw is permanent",
  "Avrupa Kulüp Havuzları": "European Club Pools",
  "TÜMÜ": "ALL",
  "Matchday Fikstür ve Sonuçları": "Matchday Fixtures and Results",
  "Bu Matchday için maç bulunmuyor.": "No matches found for this Matchday.",
  "Tüm Maçlar": "All Matches",
  "Benim Maçlarım": "My Matches",
  "Lig": "League",
  "Kupa": "Cup",
  "AKTİF GÜN": "ACTIVE DAY",
  "LİG MAÇI": "LEAGUE MATCH",
  "KUPA MAÇI": "CUP MATCH",
  "TAMAMLANAN": "COMPLETED",
  "SEZON İLERLEMESİ": "SEASON PROGRESS",
  "Rakipler Seni Hatırlıyor": "Opponents Remember You",
  "İLK TEMAS": "FIRST MEETING",
  "Rakibin özel karşı plan verisi yok": "No opponent-specific counter-plan data",
  "AKTİF REKABET": "ACTIVE RIVALRIES",
  "İlk tekrar karşılaşmalarıyla rekabet dosyaları oluşacak.": "Rivalry files will form after repeat meetings.",
  "Sezon Ödülleri": "Season Awards",
  "Yılın Menajeri": "Manager of the Year",
  "Önceki tur bekleniyor": "Waiting for previous round",
  "KURA BAYI": "DRAW BYE",
  "DOĞRUDAN TUR": "DIRECT ADVANCE",
  "TUR ATLADI": "ADVANCED",
  "Sıradaki hedef: 2 galibiyet": "Next target: 2 wins",
  "Bu tur, önceki tur tamamlandığında kura ile oluşacak.": "This round will be drawn after the previous round is completed.",
  "İlk Manager kariyeri henüz kurulmadı.": "No Manager career has been created yet.",
  "Kariyer Liderlik Tablosu": "Career Leaderboard",
  "AKTİF KARİYER": "ACTIVE CAREERS",
  "Kariyer yerel ve bulut kaydına işlendi.": "Career saved locally and to the cloud.",
  "Değişiklik cihazda korundu.": "The change was preserved on this device.",
  "Kariyer doğrulanıyor...": "Verifying career...",
  "Evren oluşturuluyor...": "Building universe...",
  "RAKİP": "OPPONENT",
  "SEN": "YOU",
  "SAĞ": "RIGHT",
  "SOL": "LEFT",
  "MERKEZ": "CENTRE",
  "ANALİZ BEKLİYOR": "AWAITING ANALYSIS",
  "Dengeli": "Balanced",
  "Kontrollü": "Controlled",
  "Güvenli": "Safe",
  "Ölçülü": "Measured",
  "Cesur": "Bold",
  "Yüksek Pres": "High Press",
  "Karşı Pres": "Counter-Press",
  "Sabırlı Kurulum": "Patient Build-Up",
  "Direkt Oyun": "Direct Play",
  "Kanatları Kullan": "Use the Flanks",
  "Hızlı Geçiş": "Fast Transition",
  "Düşük Tempo": "Low Tempo",
  "Dengeli Tempo": "Balanced Tempo",
  "Yüksek Tempo": "High Tempo",
  "Kendinize İnanın": "Believe in Yourselves",
  "Özgüven ve cesur başlangıç": "Confidence and a brave start",
  "İlk Düdükten İtibaren Baskı": "Press from the First Whistle",
  "Yüksek enerji; fizik ve kart maliyeti olabilir": "High energy; may carry fitness and card costs",
  "Sakin Kalın, Planımıza Güvenin": "Stay Calm, Trust Our Plan",
  "Kontrol, sabır ve karar kalitesi": "Control, patience and decision quality",
  "Onlara Kim Olduğumuzu Gösterin": "Show Them Who We Are",
  "Duygusal, cesur ve yüksek varyanslı": "Emotional, bold and high variance",
  "Baskı Yok, Oyunun Keyfini Çıkarın": "No Pressure, Enjoy the Game",
  "Rahatlatabilir; odağı da düşürebilir": "May relax the team but also reduce focus",
  "Duygularınızı Kontrol Edin": "Control Your Emotions",
  "Derbi ve gergin maçlarda disiplin odağı": "Discipline focus for derbies and tense matches",
  "Geçen Maçı Unutmadık": "We Have Not Forgotten the Last Match",
  "Rövanş duygusu; doğru anda ateşleyici": "Revenge emotion; energising at the right moment",
  "Bütün Baskı Onlarda": "All the Pressure Is on Them",
  "Güçlü rakibe karşı özgür ve kompakt oyun": "Freedom and compact play against a stronger opponent",
  "Kalitemizi Sahaya Yansıtın": "Show Our Quality on the Pitch",
  "Favori takımın sakin üstünlük kurması için": "For the favourite to establish calm superiority",
  "Sonucu Değil, Bir Sonraki Anı Oynayın": "Play the Next Moment, Not the Result",
  "Kötü seriden sonra zihinsel sıfırlama": "Mental reset after a poor run",
  "Bu Gece Bir Kupa Gecesi": "Tonight Is a Cup Night",
  "Oruç Reis serilerinde büyük maç enerjisi": "Big-match energy in Oruç Reis series",
  "Sorumluluğu Alın ve Cesur Oynayın": "Take Responsibility and Play Boldly",
  "Yaratıcılığı artırır; yapı kaybı yaratabilir": "Increases creativity; may weaken structure",
  "Hazırız ve kazanmak için buradayız.": "We are ready and here to win.",
  "Özgüven mesajı; favoriyken beklenti baskısı yaratabilir.": "A confidence message; may create expectation pressure as favourite.",
  "Rakibimize saygı duyuyoruz; cevabı sahada vereceğiz.": "We respect our opponent; we will answer on the pitch.",
  "Dengeli ve düşük riskli kamu mesajı.": "A balanced, low-risk public message.",
  "Baskıyı oyuncularımdan uzak tutuyorum.": "I am taking the pressure away from my players.",
  "Zor fikstürde takımı korur; favoriyken pasif algılanabilir.": "Protects the team in a difficult fixture; may seem passive as favourite.",
  "Oyuncularımdan daha fazlasını bekliyorum.": "I expect more from my players.",
  "Kötü seride reaksiyon yaratabilir veya baskıyı büyütebilir.": "May trigger a response during a poor run or increase pressure.",
  "Maçı küçük taktik ayrıntılar belirleyecek.": "Small tactical details will decide the match.",
  "Oyun okuma ve plana güven mesajı.": "A message of game reading and trust in the plan.",
  "Rakibin bizi şaşırtacağını sanmıyorum.": "I do not think the opponent will surprise us.",
  "Rakibe psikolojik baskı; yanlışsa ters teper.": "Psychological pressure on the opponent; backfires if wrong.",
  "Favori yok; her top için mücadele edeceğiz.": "There is no favourite; we will fight for every ball.",
  "Beklentiyi dengeler ve disiplin sağlar.": "Balances expectations and supports discipline.",
  "Taraftarımıza cesur bir oyun borçluyuz.": "We owe our supporters a brave performance.",
  "Atmosferi yükseltir; hücum baskısını artırır.": "Raises the atmosphere; increases attacking pressure.",
  "Çizgi Kalecisi": "Shot-Stopper",
  "Refleks ve kale savunması": "Reflexes and goal-line defence",
  "Süpürücü Kaleci": "Sweeper Keeper",
  "Savunma arkasındaki alanı kapatır": "Covers the space behind the defence",
  "Pasör Kaleci": "Distributor Keeper",
  "İlk pas kalitesini yükseltir": "Improves first-pass quality",
  "Kesici Stoper": "Stopper Centre-Back",
  "Öne çıkar ve teması erken kurar": "Steps forward and engages early",
  "Süpürücü Stoper": "Cover Centre-Back",
  "Arkaya koşuları ve derinliği korur": "Protects depth and runs in behind",
  "Top Kullanan Stoper": "Ball-Playing Centre-Back",
  "Geriden pasla oyun kurar": "Builds play from the back",
  "Geride Kalan Bek": "Stay-Back Full-Back",
  "Önce savunma güvenliği": "Defensive security first",
  "Bindiren Bek": "Overlapping Full-Back",
  "Kanatta ekstra koşu ve genişlik": "Extra runs and width on the flank",
  "İçe Kat Eden Bek": "Inverted Full-Back",
  "Merkezde pas istasyonu olur": "Becomes a central passing option",
  "Dengeli Kanat Bek": "Balanced Wing-Back",
  "İki yönlü koridor oyunu": "Two-way channel play",
  "Hücumcu Kanat Bek": "Attacking Wing-Back",
  "Son çizgiye sürekli koşu": "Constant runs to the byline",
  "Savunmacı Kanat Bek": "Defensive Wing-Back",
  "Beşli hattı korur": "Maintains the back five",
  "Çapa": "Anchor",
  "Stoperlerin önünü kapatır": "Shields the centre-backs",
  "Derin Oyun Kurucu": "Deep-Lying Playmaker",
  "İlk ve ikinci pası yönetir": "Controls the first and second pass",
  "Top Kazanan": "Ball-Winner",
  "Temas ve ikinci topları hedefler": "Targets contact and second balls",
  "Box-to-Box": "Box-to-Box",
  "İki ceza sahası arasında çalışır": "Works between both penalty areas",
  "Oyun Kurucu": "Playmaker",
  "Pas ritmini ve yönünü belirler": "Sets passing rhythm and direction",
  "Mezzala": "Mezzala",
  "Yarım alanlara hücum eder": "Attacks the half-spaces",
  "Klasik 10": "Classic No. 10",
  "Hatlar arasında oyun kurar": "Creates between the lines",
  "Gölge Forvet": "Shadow Striker",
  "Ceza sahasına geç koşu yapar": "Makes late runs into the box",
  "Serbest Rol": "Free Role",
  "Konum özgürlüğü ve yaratıcılık": "Positional freedom and creativity",
  "Çizgi Oyuncusu": "Touchline Winger",
  "Genişlik ve orta tehdidi": "Width and crossing threat",
  "İçe Kat Eden Kanat": "Inverted Winger",
  "Şut ve merkez kombinasyonu": "Shooting and central combinations",
  "Kanat Oyun Kurucu": "Wide Playmaker",
  "Dış koridordan pas üretir": "Creates passes from the outer channel",
  "Bitirici": "Poacher",
  "Ceza sahasında son dokunuş": "Final touch inside the box",
  "Hedef Oyuncu": "Target Forward",
  "Top saklar ve ikinci koşuları besler": "Holds the ball and feeds supporting runs",
  "Sahte Dokuz": "False Nine",
  "Geri gelerek merkezde üstünlük kurar": "Drops deep to create central superiority",
  "Komple Forvet": "Complete Forward",
  "Koşu, bağlantı ve bitiricilik dengesi": "Balance of running, linking and finishing",
  "TOP BİZDEYKEN": "IN POSSESSION",
  "Sabırlı Dolaşım": "Patient Circulation",
  "Boşluğu bekle, pas bağlantısını koru": "Wait for space and preserve passing connections",
  "Pozisyon Oyunu": "Positional Play",
  "Hatlar ve koridorlar arasında dengeli yerleş": "Maintain balanced positioning across lines and channels",
  "Dikine İlerleme": "Vertical Progression",
  "İlk fırsatta hat kıran pası ara": "Look for a line-breaking pass at the first opportunity",
  "Beşli Hücum Hattı": "Five-Man Attacking Line",
  "Son hatta sayıyı artır; geride alan bırak": "Add numbers to the last line; leave space behind",
  "TOP RAKİPTEYKEN": "OUT OF POSSESSION",
  "Kompakt Derin Blok": "Compact Deep Block",
  "Ceza sahası çevresini ve merkezi kapat": "Protect the centre and the area around the box",
  "Orta Blok": "Mid Block",
  "Mesafeleri koru, merkezde karşıla": "Keep distances and engage centrally",
  "Önde Baskı": "High Press",
  "Kurulumu boz; pres kırılırsa alan bırak": "Disrupt build-up; leave space if the press is beaten",
  "Adam Odaklı Baskı": "Man-Oriented Press",
  "Pas istasyonlarını takip et; yapı esneyebilir": "Track passing options; the structure may stretch",
  "TOPU KAZANINCA": "AFTER WINNING POSSESSION",
  "Önce Güvence": "Secure Possession First",
  "İlk pası koru ve yeniden yerleş": "Protect the first pass and reorganise",
  "Hızlı Kontra": "Fast Counter",
  "Boş alana ilk üç pasla hücum et": "Attack open space with the first three passes",
  "Kanada Çık": "Release to the Flank",
  "Topu baskının uzağındaki koridora taşı": "Move the ball to the channel away from pressure",
  "Direkt Çıkış": "Direct Release",
  "İlk baskı hattını tek pasla geç": "Beat the first pressure line with one pass",
  "TOPU KAYBEDİNCE": "AFTER LOSING POSSESSION",
  "Hızla Yerleş": "Recover Shape Quickly",
  "Koşu yolunu kapat ve blok halinde geri dön": "Close the running lane and recover as a block",
  "Beş Saniye Baskı": "Five-Second Press",
  "Yakındaki oyuncularla topu hemen geri ara": "Immediately hunt the ball with nearby players",
  "Pas Kanalını Kapat": "Close the Passing Lane",
  "İlk olarak dikine pas kanalını kapat": "First close the vertical passing lane",
  "Geçişi Faulle Kes": "Stop the Transition with a Foul",
  "Kontrayı durdurur; kart riskini belirgin artırır": "Stops the counter; significantly increases card risk",
  "60'tan sonra gerideysek yüklen": "Push Forward If Trailing After 60",
  "Hücum ve tempo artar; geçiş güvenliği azalır": "Attack and tempo increase; transition security decreases",
  "70'ten sonra öndeysek koru": "Protect the Lead After 70",
  "Blok ve top kontrolü güçlenir": "The block and ball control become stronger",
  "Fizik %60 altına düşerse sakinleş": "Slow Down If Fitness Drops Below 60%",
  "Tempo ve pres maliyetini otomatik azaltır": "Automatically reduces tempo and pressing cost",
  "Rakip kırmızı görürse sahayı genişlet": "Expand the Pitch If the Opponent Sees Red",
  "Sayısal üstünlükte alan ve pas açısı üretir": "Creates space and passing angles with numerical superiority",
  "Biz kırmızı görürsek kompaktlaş": "Become Compact If We See Red",
  "Merkezi kapatır ve risk seviyesini düşürür": "Protects the centre and lowers risk",
  "75'te skor eşitse kontrollü risk al": "Take Controlled Risks If Level at 75",
  "Son bölümde ölçülü bir hücum dalgası": "A measured attacking wave late in the match",
  "Oyunu sakinleştir, boşluğu bekle": "Calm the game and wait for space",
  "Hatlar arası dengeyi koru": "Maintain balance between the lines",
  "Agresif": "Aggressive",
  "Erken baskı; fizik, kart ve geçiş riski yüksek": "Early pressure with high fitness, card and transition risk",
  "Kontra": "Counter",
  "Alan bırak, geçiş anını cezalandır": "Concede territory and punish transitions",
  "Kontrol": "Control",
  "Tempo ve konum üstünlüğü kur": "Establish tempo and positional superiority",
  "Derin Blok": "Deep Block",
  "Alan daralt, arkayı koru": "Reduce space and protect the area behind",
  "Rakibi çıkışta boğ; pres kırılırsa büyük alan bırak": "Suffocate build-up; leave major space if beaten",
  "Top kaybında kısa ve sert baskı": "Short, intense pressure after losing the ball",
  "Pas açılarını çoğalt": "Create more passing angles",
  "Az pasla son bölgeye git": "Reach the final third with fewer passes",
  "Sahayı genişlet ve çizgiyi zorla": "Stretch the pitch and attack the touchline",
  "Top kazanır kazanmaz ileri çık": "Break forward immediately after winning the ball",
  "Maçı kontrol altında tut": "Keep the match under control",
  "Duruma göre hızlan": "Increase speed according to the situation",
  "Rakibe düşünme süresi verme; hata ve fizik maliyeti": "Deny the opponent thinking time; carries error and fitness costs",
  "Top kaybını ve açık alanı azalt": "Reduce turnovers and exposed space",
  "Fırsat oluştuğunda risk al": "Take risks when the opportunity appears",
  "Daha fazla oyuncuyla hücuma çık; arkada alan bırak": "Attack with more players; leave space behind"
};
  Object.entries(extraExact).forEach(([tr,en]) => exact.set(tr,en));
  const managerPatterns = [
    [/^SEZON (\\d+)$/i, "SEASON $1"],
    [/^Son kayıt:\\s*(.+)$/i, "Last save: $1"],
    [/^Son resmî kayıt:\\s*(.+)$/i, "Latest official save: $1"],
    [/^Son test kaydı:\\s*(.+)$/i, "Latest test save: $1"],
    [/^(.+) kariyeri açıldı\\.$/i, "$1 career opened."],
    [/^(.+) kariyeri için kayıt bulunamadı\\.$/i, "No save was found for the $1 career."],
    [/^Kariyer S(\\d+) yuvasına kaydedildi\\.$/i, "Career saved to slot S$1."],
    [/^S(\\d+) kaydı yüklendi\\.$/i, "Slot S$1 loaded."],
    [/^(.+) yönetiminde bağımsız kariyer\\. FC 25 kulüp kurası, rakip ELO gücü ve gizli oyun tarzı aynı maç state[\'’]inde birleşecek\\.$/i, "An independent career managed by $1. The FC 25 club draw, opponent ELO strength and hidden playing style combine in the same match state."],
    [/^(\\d+) maç tamamlandı$/i, "$1 matches completed"],
    [/^(\\d+) Menajer · 24 Maç$/i, "$1 Managers · 24 Matches"],
    [/^(\\d+) maçlık davranış verisi$/i, "$1 matches of behavioural data"],
    [/^(\\d+) MAÇLIK EVREN$/i, "$1-MATCH UNIVERSE"],
    [/^Maç başı (.+)$/i, "Per match $1"],
    [/^(\\d+) maçta 1$/i, "1 every $1 matches"],
    [/^Sezon (\\d+) başladı\\.$/i, "Season $1 started."]
  ];
  managerPatterns.forEach(row => patterns.unshift(row));

  const phrasePairs = [
    ["Kariyerden Çık","Exit Career"],["Resmî Kariyer","Official Career"],["Test Kariyeri","Test Career"],["Kariyer Puanı","Career Points"],["Kariyer","Career"],
    ["Maç Günü","Matchday"],["Maç Raporu","Match Report"],["Maç Planı","Match Plan"],["Maç","Match"],["Takım Kurası","Team Draw"],["Takım","Team"],["Rakip","Opponent"],["Oyuncu","Player"],
    ["İstatistik Merkezi","Statistics Centre"],["İstatistik","Statistics"],["Fikstür","Fixtures"],["Sonuçları","Results"],["Sonuç","Result"],["Sezon","Season"],["Devre","Leg"],["Lig","League"],["Kupa","Cup"],
    ["Hücum","Attack"],["Savunma","Defence"],["Kontrol","Control"],["Baskı","Press"],["Taktik","Tactical"],["Oyun","Play"],["Gol","Goal"],["Şut","Shot"],["Pas","Pass"],["Korner","Corner"],["Faul","Foul"],["Kart","Card"],["Penaltı","Penalty"],
    ["Kaydedildi","Saved"],["Kaydet","Save"],["Yükle","Load"],["Aç","Open"],["Kapat","Close"],["Başlat","Start"],["Devam Et","Continue"],["Bekleniyor","Pending"],["Tamamlandı","Completed"],["Henüz","Not yet"],
    ["Güçlü","Strong"],["Güç","Power"],["Yüksek","High"],["Düşük","Low"],["Dengeli","Balanced"],["Resmî","Official"],["Yerel","Local"],["Canlı","Live"],["Ana ekran","Title screen"]
  ].sort((a,b)=>b[0].length-a[0].length);

  function readLanguage() {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === "en" || saved === "tr" ? saved : (document.documentElement.dataset.language === "en" ? "en" : "tr");
  }
  let currentLanguage = readLanguage();

  function translateString(input) {
    const raw=String(input??"");
    const leading=raw.match(/^\s*/)?.[0]||"", trailing=raw.match(/\s*$/)?.[0]||"", clean=raw.trim();
    if(!clean) return raw;
    if(exact.has(clean)) return leading+exact.get(clean)+trailing;
    if(paragraphTranslations.has(clean)) return leading+paragraphTranslations.get(clean)+trailing;
    for(const [pattern,replacement] of patterns) { pattern.lastIndex=0; if(pattern.test(clean)) { pattern.lastIndex=0; return leading+clean.replace(pattern,replacement)+trailing; } }
    let changed=clean;
    for(const [tr,en] of phrasePairs) changed=changed.split(tr).join(en);
    return leading+changed+trailing;
  }

  function translateTextNode(node,language) {
    if(!node?.parentElement || ["SCRIPT","STYLE","NOSCRIPT","TEXTAREA","CODE","PRE"].includes(node.parentElement.tagName)) return;
    if(!originalText.has(node)) originalText.set(node,node.nodeValue);
    let source=originalText.get(node);
    if(language==="en") {
      const expected=translateString(source);
      if(node.nodeValue!==source && node.nodeValue!==expected && !busy) { source=node.nodeValue; originalText.set(node,source); }
      const next=translateString(source); if(node.nodeValue!==next) node.nodeValue=next;
    } else if(node.nodeValue!==source) node.nodeValue=source;
  }

  function translateAttributes(element,language) {
    const names=["aria-label","title","placeholder","data-label"];
    if(!originalAttributes.has(element)) originalAttributes.set(element,{});
    const store=originalAttributes.get(element);
    for(const name of names) {
      if(!element.hasAttribute(name)) continue;
      if(!(name in store)) store[name]=element.getAttribute(name);
      const source=store[name], next=language==="en"?translateString(source):source;
      if(element.getAttribute(name)!==next) element.setAttribute(name,next);
    }
  }

  function translateRoot(root,language=currentLanguage) {
    if(!root) return;
    if(root.nodeType===Node.TEXT_NODE) return translateTextNode(root,language);
    if(![Node.ELEMENT_NODE,Node.DOCUMENT_NODE,Node.DOCUMENT_FRAGMENT_NODE].includes(root.nodeType)) return;
    if(root.nodeType===Node.ELEMENT_NODE) translateAttributes(root,language);
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);
    let node=walker.currentNode;
    while(node) { if(node.nodeType===Node.TEXT_NODE) translateTextNode(node,language); else if(node.nodeType===Node.ELEMENT_NODE) translateAttributes(node,language); node=walker.nextNode(); }
  }

  function updateSwitch() {
    document.querySelectorAll("[data-language-option]").forEach(btn=>{
      const active=btn.dataset.languageOption===currentLanguage;
      btn.classList.toggle("active",active); btn.setAttribute("aria-pressed",String(active));
    });
  }

  function setLanguage(language,options={}) {
    const lang=language==="en"?"en":"tr";
    currentLanguage=lang; localStorage.setItem(STORAGE_KEY,lang);
    document.documentElement.lang=lang; document.documentElement.dataset.language=lang;
    busy=true;
    try { translateRoot(document.body,lang); updateSwitch(); document.title=lang==="en"?"FIFA Tournament Hub":"FIFA Turnuva Merkezi"; } finally { busy=false; }
    if(!options.silent) {
      document.dispatchEvent(new CustomEvent("fifa-language-changed",{detail:{language:lang,source:"v44.2"}}));
      document.dispatchEvent(new CustomEvent("fifa:languagechange",{detail:{language:lang,source:"v44.2"}}));
      try { window.FIFA_APP_CONTEXT?.refreshView?.(); } catch(_) {}
      setTimeout(()=>{busy=true;try{translateRoot(document.body,lang);updateSwitch();}finally{busy=false;}},0);
    }
    return lang;
  }

  function audit() {
    const issues=[], rx=/[çğıöşüÇĞİÖŞÜ]|\b(?:maç|takım|oyuncu|kura|kariyer|sezon|devre|bekleniyor|kaydet|başlat|savunma|hücum)\b/i;
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); let node;
    while((node=walker.nextNode())) { if(node.parentElement?.closest("script,style,noscript,textarea,code,pre")) continue; const value=node.nodeValue.trim(); if(value.length>2&&rx.test(value)) issues.push(value); }
    return {count:issues.length,samples:[...new Set(issues)].slice(0,40)};
  }

  function boot() {
    document.addEventListener("click",event=>{ const button=event.target.closest?.("[data-language-option]"); if(button) setLanguage(button.dataset.languageOption); },true);
    observer=new MutationObserver(mutations=>{ if(busy) return; busy=true; try { for(const mutation of mutations) { mutation.addedNodes.forEach(node=>translateRoot(node,currentLanguage)); if(mutation.type==="characterData") translateTextNode(mutation.target,currentLanguage); } updateSwitch(); } finally { busy=false; } });
    observer.observe(document.body,{childList:true,subtree:true,characterData:true});
    setLanguage(currentLanguage,{silent:true});
  }

  const api={version:VERSION,get language(){return currentLanguage;},setLanguage,t:(tr,en)=>currentLanguage==="en"?(en||translateString(tr)):tr,translate:translateString,audit};
  window.FIFA_I18N=api; window.FIFA_LANGUAGE=api;
  if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",boot,{once:true}); else boot();
})();
